### ISSUE TITLE
width/height not saved when changed by context menu

### ISSUE THREAD

**Issue by eyemd** [netresearch/t3x-rte_ckeditor_image#1]
When I change width/height by the context menu, the image path changes from absolute to relative. When saving, it reverts to the original image dimensions (and the original, absolute path).

This doesn't happen, when I change width/height in the other properties dialog by double clicking the image: It keeps the path untouched and the edited dimensions are saved.

**Comment by copitz** [comment]
Hi,

thank you - we'll look into that with the next patch version of TYPO3 Core.

Cheers,
Christian

**Comment by eyemd** [comment]
Vielen Dank für Ihre Nachricht.
  
 Ich bin dienstags jeweils nicht im Büro. Ihre E-Mail wird nicht weitergeleitet.
Bei Nachfragen erreichen Sie meine Kollegen telefonisch via 061 416 91 81 oder per E-Mail an info@eye.ch.
  
 Freundliche Grüsse
Martino Decarolis

**Comment by copitz** [comment]
Hi,

the dialog shown when doubleclick is the CKEditor dialog and it shouldn't have happened that you see this at all (see #6). With the correct dialog at least for me everything is working as expected.
