### ISSUE TITLE
 data-title="Error: no file object"

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#10]
i have updated to rte_ckeditor_image 8.7.3 and added

`lib.contentElement.settings.media.popup.enable = 1`

to my setup.

the lightbox works but the a-tag shows data-title="Error: no file object" (unimportant if filled or not).

**Comment by copitz** [comment]
Hi @wini2,

I can imagine why this happens but can't reproduce it. Can you please check out the extension at master (1e8d1b8) and see if this solves the problem?

Thank you

**Comment by prdt3e** [comment]
solution approach:
https://github.com/netresearch/t3x-rte_ckeditor_image/issues/20

**Comment by muh-nr** [comment]
That should be solved, right?
