### ISSUE TITLE
click-enlarge not working (dev-TYPO3_10.x /TYPO3 10.4.9)

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#100]
hello,

extension seems to work as expected - beside the click-enlarge-feautre (size, title- and alt-tag are rendered) .

constants:
styles.content.textmedia.linkWrap.lightboxEnabled =1
styles.content.textmedia.linkWrap.lightboxCssClass = lightbox

the a-tag is completely missing.

something i overlooked?

**Comment by mcmulman** [comment]
Hi @wini2,
please specify the versions you're working with, thanks.

**Comment by wini2** [comment]
Hi, I'm using the 10dev-version from October 2020 (t3x-rte_ckeditor_image/tree/dev-TYPO3_10.x/ 'version' => '10.0.0',).

**Comment by mcmulman** [comment]
Please check the new release 10.1.0 (even though we didn't change anything about lightbox or link handling).
But I couldn't reproduce the behaviour you mentioned.
