### ISSUE TITLE
Can't set width and height of image in backend inline editor

### ISSUE THREAD

**Issue by m-huether** [netresearch/t3x-rte_ckeditor_image#104]
In the TYPO3 backend, I created a content element of type "Text & Images" and in the text editor I inserted an image that is 500 x 500 px. When I open the image properties (by double clicking the image or via the context menu), set the width to a value lower than 500 and click "OK", the new value is not saved and the width is set to 500px.

I then inspected the source code and saw the in typo3image.js, function askImageAttributes(), tht in the actual version 9.0.5 you added width and heigt to "extend(filteredAttr)":
```
    $.extend(filteredAttr, {
        src: getImg.url,
        width: getImg.processed.width || getImg.width,
        height: getImg.processed.height || getImg.height,
        'data-cke-saved-src': getImg.processed.url,
        'data-htmlarea-file-uid': img.uid,
        'data-htmlarea-file-table': table
    });
```

Without the rows "width:" and "height:" (as in version 9.0.4) the image size can be edited. Is this a bug in rte_ckeditor_image or a bug in my configuration?

TYPO3/rte_ckeditor 9.5.22, rte_ckeditor_image 9.0.5

**Comment by mcmulman** [comment]
Hi @m-huether,
works for me with the same environment.

Is your Image Processing working correctly?

**Comment by m-huether** [comment]
Image Processing (Graphics/Image Magick) is disabled in my environment.

**Comment by mcmulman** [comment]
So there won't be any resizing in TYPO3.
