### ISSUE TITLE
Images getting parsed out when element is saved within a workspace

### ISSUE THREAD

**Issue by StrikeAgainst** [netresearch/t3x-rte_ckeditor_image#105]
I'm having the issue that whenever I'm operating within a workspace and want to edit an element containing images or trying to add some to an element, the images are gone. I've worked myself through the RTE configuration already, although that can't be the issue since it works fine when working on live. I guess the images get lost along the staging process of the workspaces, but I just can't figure out where and why. I know this might rather be a workspace-related issue, but does anyone here already have some experience regarding the workspaces' image handling and knows how to deal with it?

**Comment by mcmulman** [comment]
Hi @StrikeAgainst,
what versions are we talking about?

**Comment by Gitsko** [comment]
Unfortunately the problem cannot be reproduced.
