### ISSUE TITLE
Domain prefixing destroy image path if BE login is other domain

### ISSUE THREAD

**Issue by tgaertner** [netresearch/t3x-rte_ckeditor_image#111]
If set an Image its prefixed automatically in the Backend with the abs Domain path currently logged in in the Backen.
If the Frontend (Site) has an other Domain the base gets cut off - resulting in a relative path without a / in front. E.g. "uploads/some/path/image.png" stored in the database. That image can't be displayed on any subpage.

Removing the Domain in front of the image path in RTE source view, stores the path correctly with a / in the beginning. But reloading of the content element gives the domain back and an next storing the trailing / is gone again - so that's not an option for editors.

**Comment by marclindemann** [comment]
I think this is an issue with Classes/Controller/ImageRenderingController.php line 105
`'src' => $processedFile->getPublicUrl(),`
this should be 
`$imageService = GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Service\ImageService::class);
'src' => $imageService->getImageUri($processedFile),`

**Comment by tgaertner** [comment]
Can't tell for sure... don't have access to the related project anymore.

**Comment by Gitsko** [comment]
thanks for the quick reply, I think I would close the issue for now, if the problem still exists please just open it again
