### ISSUE TITLE
Ckeditor load error on trying to get element from a multiple node html text

### ISSUE THREAD

**Issue by eliasfernandez** [netresearch/t3x-rte_ckeditor_image#113]
When html loaded from a field is not wrapped on nodes js fails on line 30:

`$shadowEditor = $(editor.element.$.innerText),`

Forcing a wrap of the innerText value solves it:

`$shadowEditor = $("<div>").append(editor.element.$.innerText),`

It is possible when rte is configured to not autowrap empty lines with `<p>` tags

**Comment by mcmulman** [comment]
solved by #114
