### ISSUE TITLE
Images may not be updated when editor loads

### ISSUE THREAD

**Issue by cricog** [netresearch/t3x-rte_ckeditor_image#119]
Depending on the server/network speed and the client JS speed, images may not be updated when the editor loads, because the update is done before the editor content is ready.

The following patch seems to correct the issue.

```
# git diff Resources/Public/JavaScript/Plugins/typo3image.js
diff --git a/Resources/Public/JavaScript/Plugins/typo3image.js b/Resources/Public/JavaScript/Plugins/typo3image.js
index 00f956a..0eb24a9 100644
--- a/Resources/Public/JavaScript/Plugins/typo3image.js
+++ b/Resources/Public/JavaScript/Plugins/typo3image.js
@@ -73,13 +73,17 @@
                     }

                     $.getJSON(url, function(newImg) {
-                        var realEditor = $('#cke_' + editor.element.$.id).find('iframe').contents().find('body'),
-                            newImgUrl = newImg.processed.url || newImg.url;
-
-                        // Replace current url with updated one
-                        if ($curImg.attr('src') && newImgUrl) {
-                            realEditor.html(realEditor.html().replaceAll($curImg.attr('src'), newImgUrl));
-                        }
+                        // The iframe body may not be ready yet!
+                        editor.on( 'contentDom', function(event) {
+                            var newImgUrl = newImg.processed.url || newImg.url,
+                                realEditor;
+
+                            if (newImgUrl) {
+                                // Replace current url with updated one
+                                realEditor = $('#cke_' + editor.element.$.id).find('iframe').contents().find('body');
+                                realEditor.html(realEditor.html().replaceAll($curImg.attr('src'), newImgUrl));
+                            }
+                        });
                     });
                 });
             }
```

**Comment by Abdull** [comment]
@vellip 's merge request https://github.com/vellip/t3x-rte_ckeditor_image/commit/097735a8722dc605746104d0602d50eb2e467030 (i.e., changing `lib.parseFunc` to `lib.parseFunc_RTE` fixed _this_ issue for us.

That merge request got merged, [but a day later it got reverted](https://github.com/netresearch/t3x-rte_ckeditor_image/commits/master/Configuration/TypoScript/ImageRendering/setup.txt).

@mcmulman , is there a reason you reverted it?

Otherwise it would be great to change `lib.parseFunc` to `lib.parseFunc_RTE` again.

**Comment by Abdull** [comment]
As a workaround, require the specific commit before aforementioned revert commit (see https://github.com/netresearch/t3x-rte_ckeditor_image/commits/master ):

```
"netresearch/rte-ckeditor-image": "dev-master#58e8b6ac7b603551864b40b217e6f56a0e5b24ca",
```

**Comment by dogawaf** [comment]
Related to #110 and #122

Also, on slow connection/without warmed browser cache, I got another error (TYPO3 10.4.13):

![Selection_999(011)](https://user-images.githubusercontent.com/381969/111598922-01518880-87d0-11eb-92ed-a7f61421574a.png)

I think the whole CKEditor plugin integration should be rewritten and ideally without the dependency to jquery.

**Comment by dogawaf** [comment]
In the meantime, I attached a working patch.


[rte_ckeditor_image_fix_js_error.patch.txt](https://github.com/netresearch/t3x-rte_ckeditor_image/files/6202997/rte_ckeditor_image_fix_js_error.patch.txt)

**Comment by mcmulman** [comment]
@cricog 
@dogawaf 

Thanks for helping. Please check #128 (together with #127)

**Comment by Gitsko** [comment]
Hi @cricog, the problem should no longer occur with the current version (v11.0.14)

**Comment by cricog** [comment]
Sorry. Won't be able to confirm until several weeks.
Was pretty easy to reproduce (by example using devtool network throttling + no cache + large image).

**Comment by aseemann** [comment]
Tested wir slow 3G Connection and image larger 2 MiB. Works perfect so far. Close issue.
