### ISSUE TITLE
CKEditor is not loaded after -not cached- page preview from backend

### ISSUE THREAD

**Issue by lucmuller** [netresearch/t3x-rte_ckeditor_image#122]
This is a little bit tricky !
In rte_ckeditor_image/Resources/Public/JavaScript/Plugins/typo3image.js
There's a problem with :
`require(['jquery'], function (jquery) {`

As the $ variable is initialiased at the begining of the code, if Jquery is not loaded properly, then the rest of the code depending on $ fails.

A quick workaround for this is to simply comment out the line :
`//var $;`

Step to reproduce the anomaly :
- Clear The caches of the page
- Click the preview button
- Wait for the page to be **fully** loaded
- Go back to the backend editor
- Ckeditor is not loaded anymore.
See :
![image](https://user-images.githubusercontent.com/1927963/110348757-44726580-8032-11eb-9acb-ddcc7f170a03.png)

**Comment by lucmuller** [comment]
Maybe linked #110

**Comment by dogawaf** [comment]
The whole code should be wrapped by 
`
require(['jquery'], function ($) {
  // all code dependent on $ here  
});
`

**Comment by dogawaf** [comment]
I've attached a working patch in #119

**Comment by mcmulman** [comment]
Thanks @dogawaf 
@lucmuller please check again with #127

**Comment by jproy418** [comment]
Hi thanks for that fix! It's working for me. 
Is a merge in the master (or a new release of the extension) planned soon  ? 

Thanks!

**Comment by Patta** [comment]
I can also confirm this issue with TYPO3 10.4.18. #127 seems to fix this.

**Comment by Patta** [comment]
@CybotTM there is no fix for v10 for TYPO3 10.4 ?

**Comment by CybotTM** [comment]
Hi @Patta , please see release 10.2.0 if it works for you.

Cheers.

**Comment by Patta** [comment]
@CybotTM thanks for the fast release! Works nice. Just the image icon is lightened and has the `cke_button_disabled` class. 
![image](https://user-images.githubusercontent.com/2151127/146533180-ecd783cb-31b8-4480-be6e-0f14d4e902d8.png)

**Comment by lucmuller** [comment]
@Patta +1

Seems to work too, but the disabled styled icons is a bit confusing to deploy in production for contributors.

**Comment by CybotTM** [comment]
@Patta or @lucmuller, can you please create a new issue, thank you.
And of course, if you have a patch - please send.

Thank you.

**Comment by lucmuller** [comment]
New issue is created (#145), but I do not have a patch right now.
