### ISSUE TITLE
New tag / version for packagist

### ISSUE THREAD

**Issue by mueller-sebastian** [netresearch/t3x-rte_ckeditor_image#124]
Hey there,
thank you for your extension!

It would be really great if you could add a new tag/version so the regular version instead of dev-master could be used to fetch the current version of your extension.

Greetings,
Sebastian

**Comment by Gitsko** [comment]
Hi @mueller-sebastian,

I'm glad you like the extension. 
meanwhile there are new versions in the TER or on packagist
