### ISSUE TITLE
Wrong link generation in mail templates

### ISSUE THREAD

**Issue by rimmeh8** [netresearch/t3x-rte_ckeditor_image#125]
Typo3 9.5.20
rte_ckeditor_image : 9.0.5

RTE Input Backend:

`<p><img alt="" data-htmlarea-file-uid="87867" src="https://www.mydomain.de/fileadmin/user_upload/mail/logo-mail.jpg" style="height:106px; width:250px" /></p>`

Output in Mail:
`<p><img src="fileadmin/user_upload/mail/logo-mail.jpg" width="250" height="106" /></p>`

It cuts the Toplevel Domain in Link SRC, so it cant be displayed in the email which is sent by powermail.

**Comment by Geddo** [comment]
+1

**Comment by patrickmsieber** [comment]
Got the same issue with TYPO3 11.5.12

Is there already a solution for this issue or is there a similar issue solved?

**Comment by just-tobi** [comment]
Hi Guys,

sorry for the big delay - we will jump into it an check the problem.

**Comment by prdt3e** [comment]
Hello,
the solution is simple:
config.absRefPrefix = https://domain.com

The images via the editor behave like fluid and can be adjusted with Typoscript.
If nothing of the sort has been changed in the code, it should still behave like this.

**Comment by Gitsko** [comment]
Hi @rimmeh8,

i hope the answer from @prdt3e can help you, if not please open the issue again.
