### ISSUE TITLE
Wrong link image

### ISSUE THREAD

**Issue by mohammed-bens** [netresearch/t3x-rte_ckeditor_image#126]
Typo3 10.4.13
rte_ckeditor_image : 10.1.0

RTE Input Backend:

&lt;p&gt;&lt;img alt=&quot;&quot; data-htmlarea-file-table=&quot;sys_file&quot; data-htmlarea-file-uid=&quot;8195&quot; height=&quot;49&quot; src=&quot;{domaine}/typo3/index.php?route=%2Fimage%2Fprocess&amp;amp;token=689e21a7b706676a3658aaccedd070d5617e11f2&amp;amp;id=11006&quot; title=&quot;&quot; width=&quot;150&quot; /&gt;&lt;/p&gt;

if I do a second time with the same width i have:

&lt;p&gt;&lt;img alt=&quot;&quot; data-htmlarea-file-table=&quot;sys_file&quot; data-htmlarea-file-uid=&quot;8195&quot; height=&quot;49&quot; src=&quot;{domaine}/fileadmin/images/png/3_decale_p.png&quot; title=&quot;&quot; width=&quot;150&quot; /&gt;&lt;/p&gt;

**Comment by davkraid** [comment]
Same issue here.

**Comment by 126016** [comment]
Same issue here.
