### ISSUE TITLE
data-htmlarea attributes shown on frontend

### ISSUE THREAD

**Issue by rdk-pmis** [netresearch/t3x-rte_ckeditor_image#13]
The properties data-htmlarea-file-table and data-htmlarea-file-uid are shown in the frontend. They serve no purpose there and should be removed.

**Comment by derhansen** [comment]
This may occur, if `lib.parseFunc` is not included somehow. You could check the TypoScript setup of your site in the TypoScript ObjectBrowser if `preUserFunc` is configured as shown below

![image](https://user-images.githubusercontent.com/2629896/29509664-52572bd0-8659-11e7-90dc-33e57580bea8.png)

**Comment by copitz** [comment]
Thank you both for clearing this up for later reference

**Comment by rdk-pmis** [comment]
I've checked and both lib.parseFunc and lib.parseFunc_RTE contain that 
entry.
In my case I didn't include a parseFunc in my renderingcode for that 
part of my code.
I've changed my code to include the tag handling, but it didn't help.
The actual code that solves this `parseFunc.nonTypoTagStdWrap.HTMLparser 
< lib.parseFunc.nonTypoTagStdWrap.HTMLparser`
