### ISSUE TITLE
Plans for TPYO3 11LTS version of t3x-rte_ckeditor_image?

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#135]
Hi,

not a bug but a question if there will be a new version for TYPO3 11 in the near future.

If I try to use version 10.1.0 with TYPO3 11 it ends up with the error-message
Class 'Netresearch\RteCKEditorImage\Database\RteImagesSoftReferenceIndex' not found

thank you for your respond
wini2

**Comment by MIchelHolz** [comment]
Here some changes i.o for the Controllers to work with 11LTS:
+ Adjust Route.php to include mode=file parameter
+ Adjust RteImagesSoftReferenceIndex class declaration to extend TypolinkSoftReferenceParser and implement SingletonInterface as in TYPO3\CMS\Core\Database\SoftReferenceIndex::class
+ typo3image.js should be adjusted to the frontend changes in 11LTS backend.

**Comment by wini2** [comment]
Thank for the tips, but regrettably they are a little less detailed for me as non-developer. It would be very kind if you could a more comprehensive explanation.

**Comment by MIchelHolz** [comment]
This worked for me so far:

[Routes.php.diff.txt](https://github.com/netresearch/t3x-rte_ckeditor_image/files/7486297/Routes.php.diff.txt)
[RteImagesSoftReferenceIndex.php.diff.txt](https://github.com/netresearch/t3x-rte_ckeditor_image/files/7486298/RteImagesSoftReferenceIndex.php.diff.txt)
[SelectImageController.php.diff.txt](https://github.com/netresearch/t3x-rte_ckeditor_image/files/7486299/SelectImageController.php.diff.txt)
[typo3image.js.diff.txt](https://github.com/netresearch/t3x-rte_ckeditor_image/files/7486300/typo3image.js.diff.txt)

waiting for the developer to publish 11LTS support for this extension ;)
