### ISSUE TITLE
Broken image if inserted from non-publicly available file storage

### ISSUE THREAD

**Issue by xperseguers** [netresearch/t3x-rte_ckeditor_image#15]
When an image is embedded into the RTE from a file storage which is not publicly accessible (and in my case with EXT:fal_securedownload enabled but should not be related):

- The image is shown in Frontend when the user is currently logged into the Backend
- The image is not shown, in fact its markup is wrong 

The image is embedded as following in RTE:

```
<p><img alt="" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="30428" height="145" src="http://www.domain.tld/fileadmin/user_upload/1.jpg" width="145" /></p>
```

Now, protect file storage "fileadmin":

- Go to pid 0 with Web > List
- Edit file storage for fileadmin
- Under Access capabilities, uncheck "Is publicly available?" and save

Go back to the record, remove the existing picture and insert it again.

Image is now embedded as following in RTE:

```
<img data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="30428" height="145" src="..//typo3/index.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;eID=dumpFile&amp;t=f&amp;f=30428&amp;token=bb5e48e985d21573de990c36120e2bad5e625d3e&amp;ajaxToken=22f5be309fb46edc28547a08adc89c88e09bead7" width="145" />
```

In Frontend, when authenticated, every works fine, the src for HTML tag img is:

```
/typo3/index.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&eID=dumpFile&t=f&f=30428&token=bb5e48e985d21573de990c36120e2bad5e625d3e&ajaxToken=22f5be309fb46edc28547a08adc89c88e09bead7
```

This is thus a Backend link, which works since authenticated, however it fails when not authenticated.

Instead, a valid src for HTML tag img should be of the form:

```
/index.php?eID=dumpFile&t=p&p=45&token=caf8079ff290d341498377ebd78e0bbac92f5f2b
```

**Comment by xperseguers** [comment]
After some further analysis, it looks like this problem does not happen when NOT using EXT:fal_securedownload. In fact, there is another bug, which I documented in my comment from 12:51 on https://review.typo3.org/#/c/53140/8 but it's a bug in Core, not in this extension.

Will still analyse a bit before closing this ticket.

**Comment by copitz** [comment]
Thanks Xavier, very much appreciate your support!
