### ISSUE TITLE
Version of branch 10 is still 10.1.0

### ISSUE THREAD

**Issue by ste101** [netresearch/t3x-rte_ckeditor_image#150]
The version in ext_emconf.php of branch 10 is still 10.1.0

**Comment by CybotTM** [comment]
This is only required for legacy installations - which we usually do not support.

https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/LegacyInstallation.html#legacyinstallation

But let me have a look.

**Comment by CybotTM** [comment]
Hi @ste101 ,

fixed version in branches - do you also need a new release for this?

**Comment by ste101** [comment]
I don't need it necessarily but which version is in TER?
It seems to be version 10.1.0.

**Comment by CybotTM** [comment]
Yes, it is version 10.1.0.

https://extensions.typo3.org/extension/rte_ckeditor_image

But the linked packagist has all versions: https://packagist.org/packages/netresearch/rte-ckeditor-image

It seems TER has a problem with renaming composer package name from `netresearch/rte_ckeditor_image` to `netresearch/rte-ckeditor-image`.

And you cannot just update the extensions with the new packagist/composer package name.

![image](https://user-images.githubusercontent.com/326348/149637140-a9c8c60a-441c-4c5c-8031-82e79ca18bdb.png)

**Comment by CybotTM** [comment]
mhm, got it, uploaded them now manually.

Need to automate this ...

**Comment by davidlemaitre** [comment]
I was surprised after updating to v10.2.1 that backend module still displays 10.1.0 version. The version in the ext_emconf.php file should be corresponding to the tag version.
