### ISSUE TITLE
TypolinkSoftReferenceParser not found

### ISSUE THREAD

**Issue by karelkuijpers** [netresearch/t3x-rte_ckeditor_image#155]
Since typo3 version 10.4.24 I get this error when saving content with an image:
Class 'TYPO3\CMS\Core\DataHandling\SoftReference\TypolinkSoftReferenceParser' not found

in /var/www/accept2/public/typo3conf/ext/rte_ckeditor_image/Classes/Database/RteImagesSoftReferenceIndex.php line 24
 * @author     Stefan Galinski <stefan@sgalinski.de>
 * @license    http://www.gnu.de/documents/gpl-2.0.de.html GPL 2.0+
 * @link       http://www.netresearch.de
 */
class RteImagesSoftReferenceIndex extends TypolinkSoftReferenceParser implements SingletonInterface
{
    /**
     * Token prefix
     */

**Comment by Gitsko** [comment]
Hi @karelkuijpers, it shoud be work since version 11.0.0, can you confirm this ?

**Comment by Gitsko** [comment]
no answer here, I close the issue, should the problem arise again please open the issue again

**Comment by xerc** [comment]
fyi/ as written [above](https://github.com/netresearch/t3x-rte_ckeditor_image/issues/155#issuecomment-1124000126) the version `v11.0.0` has `v10` within spec. which is wrong
https://github.com/netresearch/t3x-rte_ckeditor_image/blob/b2bb458fa051ccf1718bc51d79815396049200ce/ext_emconf.php#L13-L14
