### ISSUE TITLE
Images shown but lightbox not working

### ISSUE THREAD

**Issue by wolfgang007** [netresearch/t3x-rte_ckeditor_image#158]
Hello, 

the images are shown correctly, but the lightbox doesn't work. Any ideas?

`styles.content.textmedia.linkWrap.lightboxEnabled = 1` is set. 

Output: 
`<img alt="" data-alt-override="true" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="33" data-htmlarea-zoom="true" data-title-override="true" src="/fileadmin/_processed_/5/b/csm_asdf.jpg" style="" width="900" height="601">`

Typo3 v11 & rte_ckeditor_image 11.0.2

![picture](https://user-images.githubusercontent.com/17067590/156545731-3ab6acf4-75c1-4ede-b12b-b8c26d2b10e6.PNG)

Thx for help.

**Comment by agendartobias** [comment]
Hey i got same problem in TYPO3 v.11 and rte_ckeditor_image 11.0.2

**Comment by wolfgang007** [comment]
You have to include the static template before the Fluid Styled content template. 

That worked for me ;-)

**Comment by Gitsko** [comment]
Hi @agendartobias,
have you set the TYPO3 constant `styles.content.imgtext.linkWrap.lightboxCssClass` ? See also [here ](https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Functions/Imagelinkwrap.html)

**Comment by arnekolja** [comment]
Same here with TYPO3 10 LTS and rte_ckeditor_image 10.2.5.

@agendartobias Have you been able to solve this somehow?

**Comment by Gitsko** [comment]
hi @arnekolja, 

the TYPO3 constant `styles.content.imgtext.linkWrap.lightboxCssClass` does not help at this point ?

**Comment by arnekolja** [comment]
@Gitsko Never mind, I just found out that the still-in-use old version of the bootstrap_package was clearing `lib.contentElement.settings.media.popup` which caused the wrong behavior.

**Comment by Gitsko** [comment]
Good news, thanks for the information.
