### ISSUE TITLE
Maximum width/height doesn't get respected

### ISSUE THREAD

**Issue by marceltoepler** [netresearch/t3x-rte_ckeditor_image#16]
I set up fresh TYPO3 8.7.4 with `rte_ckeditor_image`.

I put 
```
# Page TSConfig
RTE.default.buttons.image.options.magic {
    maxWidth = 1020  # Default: 300
    maxHeight = 800  # Default: 1000
}
```
in my Page TSConfig, but when I try to insert an image I cannot increase the image width more than 300.

Did I do something wrong?

Thank you!

**Comment by copitz** [comment]
Is the image wider than 300px?

**Comment by marceltoepler** [comment]
Yes, more than 1000px.

**Comment by Sebastian-Habiger** [comment]
I had an similar issue with typo3 8.7.4. I was not able to change the image size within ckeditor. After pressing save the image size changed back to its original size.

A fix/ workaround was to change line 41 in typo3image.js and remove '../' of ...src: '../' + img.processed.url,..

SelectImageController returns 'fileadmin/....' and therefore '../fileadmin/..' does not point to a valid file.

Hopefully this helps

**Comment by muh-nr** [comment]
Is this still an issue?
I can't reproduce.
