### ISSUE TITLE
Backend: Doubleclick on an image with link and zoom function leads to two overlays (edge case?)

### ISSUE THREAD

**Issue by 3l73** [netresearch/t3x-rte_ckeditor_image#163]
A doubleclick on an image with link and zoom function leads to two overlays.
None of the overlays is accessable and could not be closed either.

## How to test

1. Create a simple text element and add an image
2. Activate the Zoom function
3. Wrap the image within a link
4. Doubleclick on the image

The overlay for links and the image settings open. Both are not accessable and can not be closed.

## Expected behaviour

Only the link overlay should open?

## Additional information

TYPO3 version:  11.5.8
Extension version:  dev-master (Hash: 20297bba7300cd4d960e6e985d402aeeadc07d7f)

**Comment by magicsunday** [comment]
Same as #186 ?

**Comment by Gitsko** [comment]
Hi @3l73,

the problem should be fixed with version 11.0.14. #245
