### ISSUE TITLE
Recent versions missing on Packagist

### ISSUE THREAD

**Issue by Physikbuddha** [netresearch/t3x-rte_ckeditor_image#171]
Version 11.0.3 released yesterday is not available on Packagist (dev-master is missing as well), so I have no option to pull the newest release via Composer, unless I add the Github repository as a Composer source.

It would be great to have the latest update available on Packagist. 🙂

`myproject require netresearch/rte-ckeditor-image ^11.0.3 -> found netresearch/rte-ckeditor-image[v11.0.3] in the lock file and netresearch/rte-ckeditor-image[dev-TYPO3_8.7.x, dev-TYPO3_9.x, dev-TYPO3_10, dev-i56_images-in-preview, dev-i82_lazyload, dev-i88_custom-css-class, dev-issue-119_update-images-on-editor-load, v8.7.1, ..., v8.9.0, v9.0.0, ..., v9.0.5, v10.0.0, v10.2.0, v10.2.1, v11.0.0, v11.0.1, v11.0.2] from composer repo (https://repo.packagist.org) but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one from the lock file.`

**Comment by CybotTM** [comment]
Fixed cmposer.json and releaased 11.0.4 - now also available on packagist, along with dev-master.

Thanks for reporting.
