### ISSUE TITLE
removeItems does not work

### ISSUE THREAD

**Issue by mattleiser** [netresearch/t3x-rte_ckeditor_image#181]
Hello
I'm using TYPO3 11 and RTE CKEditor-image 11.0.2 and want to disable class and clickentlarge in the image properties dialog. That doesn't work, tried:
RTE.default.buttons.image.properties.removeItems = clickenlarge,class
RTE.default.buttons.image.properties.magic.removeItems = clickenlarge,class
RTE.default.buttons.image.options.removeItems = clickenlarge,class
RTE.default.buttons.image.options.magic.removeItems = clickenlarge,class
What am I doing wrong or does it not work.

Greeting
Matthias

**Comment by mattleiser** [comment]
A solution could be as follows:
Resources/Public/JavaScript/Plugins/typo3image.js
Line 568:
if (typeof editor.config.typo3image.zoom === "undefined" || editor.config.typo3image.zoom.disabled !== "undefined" && editor.config.typo3image.zoom.disabled !== 1) {

and Line 574:
if (typeof editor.config.typo3image.cssClass === "undefined" || editor.config.typo3image.cssClass.disabled !== "undefined" && editor.config.typo3image.cssClass.disabled !== 1) {

In my RTE config yaml I can then set the option as follows:
  externalPlugins:
    typo3image:
      allowedExtensions: "gif,jpg,jpeg,png,svg"
      zoom:
        disabled: 1
      cssClass:
        disabled: 1

**Comment by AndreasMueller75** [comment]
This is very special. We don't want to make the image properties so extrem customizable.  The user/editor can fill/check or let them untouched.
If you really want to, then you can do it like your proposal. Add the options in your RTE Config to typo3image and check editor.config.t3image.whatever in rte_ckeditor_image/Resources/Public/JavaScript/Plugins/typo3image.js before the checkbox and input field are added to the editor.
But we will not include something like that.
