### ISSUE TITLE
Inline image with link sometimes causes incorrect ordering of double-

### ISSUE THREAD

**Issue by Abdull** [netresearch/t3x-rte_ckeditor_image#186]
Using **TYPO3 11.5.14** with **rte_ckeditor_image v11.0.5**.

When an inline image has a link, double-clicking the image in the CKEditor opens two modals at once:
* TYPO3's modal "Link Browser" for selecting the link target
* Above the "Link Browser" modal, rte_ckeditor_image's modal for changing the image properties (width, height ...).

Both modals each add a darkening/fade background HTML elements. Maybe due to a race condition, sometimes these background HTML elements get ordered incorrectly, causing the "Link Browser" background HTML element to be placed above the actual modals (`z-index` too high). The whole backend view then appears greyed out.

Significantly, as these background HTML elements capture and block mouse clicks, it is not possible anymore to change values, click "OK", or cancel the modals by using the mouse.

Workarounds:
* Deleting the problematic background HTML element from the DOM tree
* Using keyboard (tabbing, enter key)
* Reloading the page and trying again until the modal order is correct
* Not using doubleclick for opening both modals, but instead using the CKEditor "image" and "link" editor buttons in order to open only one modal.
![double-modal-fade](https://user-images.githubusercontent.com/529862/186402010-f0b387a5-cba8-4b7b-96c5-554ffa4b8175.png)
![double-modal-fade-html](https://user-images.githubusercontent.com/529862/186402015-ecd452ed-90dd-48fb-bb27-03685077b359.png)
![double-modal-fade-workaround](https://user-images.githubusercontent.com/529862/186402020-8ca6caf5-a3a7-412f-81c9-0cbea3b7207f.png)

**Comment by magicsunday** [comment]
@Abdull 

Please try the changes in branch GH-186, if this fixes your problem.
