### ISSUE TITLE
RTE transformations RTE => DB hook transform_db uses uninitialized $this->procOptions

### ISSUE THREAD

**Issue by sypets** [netresearch/t3x-rte_ckeditor_image#188]
The function `RteImagesDbHook::transform_db() `is called from RteHtmlParser (as hook). Beforehand, a new instance is created and the configuration $this->procOptions is not initialized.

You can confirm this by debugging and setting a breakpoint in the function and checking the content of $this->procOptions and comparing the content when a breakpoint is set in RteHtmlParser::transformTextForPersistence().  

## System

* TYPO3 11.5.16
* rte_ckeditor_image: v11.0.5

**Comment by sypets** [comment]
Also, the hook is deprecated in v11 and will be removed in TYPO3 v12.

See related:

deprecation:
* https://forge.typo3.org/issues/92992

removal:
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/72521
*

**Comment by CybotTM** [comment]
Yes, this is fixed with 34a65f3 - I was not aware of this issue here, otherwise I had linked it.
