### ISSUE TITLE
data-htmlarea-zoom="true" don't work

### ISSUE THREAD

**Issue by prdt3e** [netresearch/t3x-rte_ckeditor_image#19]
In Line 199 $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.']:

Array
(
    [bodyTag] => <body style="margin:0; background:#fff;">
    [wrap] => <a href="javascript:close();"> | </a>
    [width] => 1024
    [height] => {$styles.content.textmedia.linkWrap.height}
    [crop.] => Array
        (
            [data] => file:current:crop
        )

    [JSwindow] => 1
    [JSwindow.] => Array
        (
            [newWindow] => 0
            [if.] => Array
                (
                    [isFalse] => 1
                )

        )

    [directImageLink] => 1
    [linkParams.] => Array
        (
            [ATagParams.] => Array
                (
                    [dataWrap] => class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"
                )

        )

)

The Callback is only a Image.
lightbox[{register:content_uid}] is a Bug in Group-Function: https://forge.typo3.org/issues/72779 (https://gist.github.com/Kitzberger/acfc630c0ea9a430c875af3fbe79a724)

Thanks for Infos.

**Comment by prdt3e** [comment]
You need:  Line 117:
$GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.']['enable'] = 1;

or:
lib.contentElement.settings.media.popup.enable = 1
In TS.
fluid_styled_content settings:
styles.content.textmedia.linkWrap.lightboxEnabled = 1 // lib.contentElement.settings.media.popup.directImageLink =  {$styles.content.textmedia.linkWrap.lightboxEnabled}
for clickEnlarge.

Thanks.

**Comment by michelrossier** [comment]
Did anyone find a solution for this issue?

**Comment by prdt3e** [comment]
Write in your TS: lib.contentElement.settings.media.popup.enable = 1

**Comment by muh-nr** [comment]
Is this still a problem?
