### ISSUE TITLE
Can't resize image by changing properties

### ISSUE THREAD

**Issue by github1maxserv** [netresearch/t3x-rte_ckeditor_image#193]
If you insert an image you can set the width/height. Once the image in the RTE is saved any changes in the dialogue are ignored.
Workaround is to resize the image using the handles of the selected image.

Changing the alternative text does result in changes to be persisted. It's just the width/height that can't be changed in the dialogue.

Version: 10.2.5 (with latest TYPO3 v10.x)

**Comment by mueller-sebastian** [comment]
I guess the problem ist how the properties are saved. When inserting the rte-image and change image properties before saving or viewing source, the size can be changed. The inserted image uses the width and height attribute of the <img-tag.
If saved (or <> source is clicked), the width/height attributes are removed and saved in style="width: 222px; height: 111px;".

I have not located where I can change it but want to provide infos I've found.

**Comment by Gitsko** [comment]
Images are downsized in the current v11 and v12 versions, I close the ticket with this, if you have any questions please reopen the issue.
