### ISSUE TITLE
compressed images not being created after update (10.1 ⇒ 11.0)

### ISSUE THREAD

**Issue by dontWatchMeCode** [netresearch/t3x-rte_ckeditor_image#199]
Hello,

we are currently having a problem with the creation of processed images, after an update from:
t3: 10 ⇒ 11
php: 7.4 ⇒ 8.1

Calling the element on the frontend doesn't create a processed variant,
opening it in the backend, going to edit + saving resolves the issue and the image is displayed normally.
(doing this for all elements, sadly not really possible ~3k)

Image URL (processed) wearily stays the same (FE & BE) after the save.

![Screenshot from 2022-11-25 16-57-35](https://user-images.githubusercontent.com/84477901/204020826-a3da1de2-9e70-4c78-a2c7-1f95f96e3085.png)

![Screenshot from 2022-11-25 17-03-59](https://user-images.githubusercontent.com/84477901/204021881-8a3adb32-e5ac-4242-b915-ca6c6bc22e44.png)

I have tried:
- clear all cashes
- delete processed folder
- empty sys_file_processedfile
- +1 to the resolution variables in the controller action

note:
- mask elements
- appears in some elements which don't have images (only BE)

similar issues:
https://github.com/netresearch/t3x-rte_ckeditor_image/issues/187
https://github.com/netresearch/t3x-rte_ckeditor_image/issues/180

versions:
- mask: 7.2.15
- typo3: 11.5.19
- php: 8.1.12
- rte_ckeditor_image: 11.0.5

Any help is much appreciated!
Have a nice evening.

**Comment by OnlyPain-ctrl** [comment]
just tried branches:
- jpmschuler:bugfix-fileadminNoSlash
- master

same problem

**Comment by KotteBW** [comment]
We had the same Problem and did use a database update for the old images. 
Maybe someone has time to write a small wizard.  
UPDATE tx_news_domain_model_news SET bodytext = REPLACE(bodytext, 'src=fileadmin', 'src=/fileadmin');

**Comment by cgpro** [comment]
Same problem here. If I open the content element with the CKEditor and wait a bit, the image is processed. Bevore that, the image is not available in the frontend (404).
I don't even have to save the content element. It's really just enough to open it and wait a short while, to get the image within fileadmin/_processed_/...

- PHP 8.0
- TYPO3 11.5.25
- rte-ckeditor-image 11.0.9
- georgringer/news ^10.0

**Comment by prdt3e** [comment]
Maybe we should think about a task in the scheduler as a CLI task.
The problem also occurs when the processed folder is deleted.

**Comment by prdt3e** [comment]
@CybotTM enhancement?

**Comment by ToGetATockenOnly** [comment]
A month later, this fix fell out of the code by changes for TYPO3v12 - https://github.com/netresearch/t3x-rte_ckeditor_image/commits/main/Classes/Database/RteImagesDbHook.php

**Comment by CybotTM** [comment]
Hi @ToGetATockenOnly ,

please be so kind to open a new issue if you find an issue and do not just add comments to closed ones.
Thank You.
