### ISSUE TITLE
click-enlarge

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#2]
hello,
is it possible to enrich this very usefull extension by enableing the click-enlarge feature?
thanks

**Comment by copitz** [comment]
Hi,
thank you - yes, I think this should be possible. FYI: In general our idea was to align the versioning/release planning of this extension with that of TYPO3 Core and release new features only with the next minor version of TYPO3. (@bmack, do you think this is a good idea and do you have information about when this could be?)

However regarding click-enlarge we'd stick with the behavior of fluid_styled_content by utilizing [lib.contentElement.settings.media.popup](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_8-7/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Helper/ContentElement.txt#L21) - or do you have another recommendation?

Cheers,
Christian

**Comment by wini2** [comment]
Hi Christian,
thank you for your infromative answer. Even if I don't undersand why you release cycle is paired with the coreupdate, i have to accept it.
No good idea to ask for recommodation :))
- Something i missed in the rtehrmlarea - It would be very nice to wrap the image in a figure-tag (with the opportunity of a figcaption) - for those who don't need this feature, eventually selectable in the extension manager
- Like in the rtehtmlarea it would be useful, if an editor would be able to set the alignment, class and margin.

I'm looking forward for the next version of rte_ckeditor_image, which surely will become a standard extension.

Kind regards
wini2

**Comment by copitz** [comment]
@wini2 - yes, I'm already rethinking to stick with TYPO3 release cycle

> Like in the rtehtmlarea it would be useful, if an editor would be able to set the alignment, class and margin.
You can use styles sets in yml config for this - e.g.:

    editor:
        config:
            stylesSet:
                - { name: "Align right", element: "img", attributes: { class: "pull-right" } }

**Comment by wini2** [comment]
yes, that would work. but for normal editors this might be a little bit to difficult and confusing.

at the moment i try to make image2 work (http://ckeditor.com/addon/image2), which would bring the figure-tag to the ckeditor. i struggle with the configuration, 'caus it seems that it's not possible to use plugins outside the sysext-directory typo3_src-8.7.1/typo3/sysext/rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml. maybe it has something to do with the localconf

 'paths' => [
            'ckeditor' => \TYPO3\CMS\Core\Utility\PathUtility::getAbsoluteWebPath(
                    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('rte_ckeditor', 'Resources/Public/JavaScript/Contrib/')
                ) . 'ckeditor'
        ]

it would be great if you integrate this feature in your extension.

cheers
wini2

**Comment by frans-beech-it** [comment]
@wini2 you need to add the plugin as externalPlugin. Just like is done here with rte_ckeditor_image

https://github.com/netresearch/t3x-rte_ckeditor_image/blob/master/Configuration/RTE/Plugin.yaml

**Comment by wini2** [comment]
@frans-beech-it yes, that's right. It had something to do with the dependencies of the neccessary plugins.

making image2 work does't help, because it 'deactivated' the possibility of the imageselection-dialog of the rte_ckeditor_image (it's only possible to insert the image-url manualy).

**Comment by copitz** [comment]
Hi @wini2,

image zoom is now implemented and will be released with the next version. Given you've setup image zoom in general with at least the following TS setup:

    lib.contentElement.settings.media.popup.enable

you can now tick "Enlarge On Click" in the image properties and the image will be zoomed on click in the FE.

**Comment by copitz** [comment]
For the rest of your wishlist please open a new issue or - even better :) - pull request.

**Comment by copitz** [comment]
New version 8.7.2 is released

**Comment by wini2** [comment]
hi copitz,
thanks for your info and for implemantation. i have updated to rte_ckeditor_image 8.7.3 and added 

`lib.contentElement.settings.media.popup.enable = 1`

to my setup.

the lightbox works but the a-tag shows data-title="Error: no file object" (unimportant if filled or not). Beside that, i can't deselect the ckeckoxex for title and alt (labeled with "Set element specific value (No default)").

**Comment by copitz** [comment]
Hi @wini2 - thank you for your help.

Could you please file a new issue for that as this one is closed already and I wouldn't like to reopen it. Also could you please not mix issues (keep things granular) - thank you.

However regarding the checkbox "issue": this should be the very same behavior as you could see it with image selectors in TYPO3 (f.i. textmedia content element) - the checkbox is disabled (thus not changeable) because there is no default which means you can not use it.
