### ISSUE TITLE
Error: no file object in title

### ISSUE THREAD

**Issue by prdt3e** [netresearch/t3x-rte_ckeditor_image#20]
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"

file:current:title says Error: no file object. 
I think no refernce in imageLinkWrap.

Thanks

**Comment by prdt3e** [comment]
`if ($imageAttributes['data-htmlarea-zoom'] && isset($file) && $file) {
    
    $config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
    $config['enable'] = 1;
    $config['linkParams.']['ATagParams']= 'title="'.$imageAttributes['title'] ?: $file->getProperty('title').'" ';

    $GLOBALS['TSFE']->cObj->setCurrentFile($file);
    return $this->cObj->imageLinkWrap(
        $img, $file,
        $config
    );
}`

**Comment by prdt3e** [comment]
`
if ($imageAttributes['data-htmlarea-zoom'] && isset($file) && $file) {
    
    $config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
    $config['enable'] = 1;
    $config['linkParams.']['ATagParams']= 'title="'.$imageAttributes['title'] ?: $file->getProperty('title').'" ';

    $GLOBALS['TSFE']->cObj->setCurrentFile($file);
    return $this->cObj->imageLinkWrap(
        $img, $file,
        $config
    );
}

`

**Comment by prdt3e** [comment]
if ($imageAttributes['data-htmlarea-zoom'] && isset($file) && $file) {
    
    $config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
    $config['enable'] = 1;
    $config['linkParams.']['ATagParams']= 'title="'.$imageAttributes['title'] ?: $file->getProperty('title').'" ';

    $GLOBALS['TSFE']->cObj->setCurrentFile($file);
    return $this->cObj->imageLinkWrap(
        $img, $file,
        $config
    );
}

**Comment by wini2** [comment]
hi prdt3e,
i think this should be added in ImageRenderingController.php line 116 ?
 
i tried it with and without ts-setup 
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"
 
 lightbox still not working (TYPO3 8.7.6). 
a href="fileadmin/_processed_/4/3/csm_800px-Galuzzi_2004_ee90e60a9b.jpg" class="lightbox" title="Error: no file object" rel="lightbox[]" data-caption="Error: no file object"
 
 thanks for your help

**Comment by prdt3e** [comment]
I first noticed the following for you: rel = "lightbox []".
No uid from your gallery. But that's a Typo3 bug. It would open "all" pictures.
Look here, you are missing lines: https://gist.github.com/Kitzberger/acfc630c0ea9a430c875af3fbe79a724

To your problem:
your code in ImageRenderingController.php must look like this from line 116:

```php
if ($imageAttributes['data-htmlarea-zoom'] && isset($file) && $file) {
    
    $config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
    $config['enable'] = 1;
    $config['linkParams.']['ATagParams']= 'title="'.$imageAttributes['title'] ?: $file->getProperty('title').'" ';

    #$GLOBALS['TSFE']->cObj->setCurrentFile($file);
    return $this->cObj->imageLinkWrap(
        $img, $file,
        $config
    );
}
return $img;
```
Then empty the Typo3 cache in the installtool.

**Comment by wini2** [comment]
hi prdt3e,
thank you for your instant reply.
https://gist.github.com/Kitzberger/acfc630c0ea9a430c875af3fbe79a724 fixed rel-problem. i altered the code - line 116 as suggested, cleared cache, deleted processed files -  but with no effect.
 
would it be possible to insert the file identifiier via ts directly?

thanks for your help

**Comment by prdt3e** [comment]
Make 
print_r($GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.']);
exit();

And post your configuration.

Thanks

**Comment by muh-nr** [comment]
Is this still a problem?

**Comment by wini2** [comment]
i updated to version 8.7.5 and cleared all caches and processed files, but the problem still persists.

would you be so kind to explain how to use the print_r command mentioned above?

**Comment by muh-nr** [comment]
To  check the current configuration,below the line 
`public function renderImageAttributes($content = '', $conf) {` 
 just write the following code:
`var_dump($GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.']);
var_dump($this->getImageAttributes());
exit();
`

And post the output.

**Comment by prdt3e** [comment]
Hi wini2,
go to typo3conf/ext/rte_ckeditor_image/Classes/Controller/ImageRenderingController.php on Line 117 and make print_r($GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.']);
exit(); before RETURN;
Clear the Typo3-Cache in the Install-Tool and go to the Page with your broken Image.

I think the problem is in the a-tag Config (lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap).

**Comment by prdt3e** [comment]
@muh-nr 
i think the error occurs in the following scenario:
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file: current: title}"

I saw it in the post (10 Dec 2017) by wini2 -> data-caption =" Error: no file object ".
I think the atag (ATagParams) was manipulated with {file:current:title}.

**Comment by muh-nr** [comment]
Okay, got it...
Please add the following Template TS.
The last line disables the default TYPO3 popup function:

`lib.contentElement.settings.media.popup.enable = 1
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"
lib.contentElement.settings.media.popup.JSwindow = 0
`

**Comment by prdt3e** [comment]
@muh-nr 
Yes i know, i had described above :)
It would be better with a replace-command for ATagParams.
Replace {file:current:title} with $imageAttributes['title'].

That would be great 
Thank you for all

**Comment by muh-nr** [comment]
@prdt3e 
I just wanted to summarize the config for wini2.

But now your suggestions have been transferred to a new commit.
Please check the current master.

Thanks for your help!

**Comment by muh-nr** [comment]
Thanks, didn't know about that.
It's fixed within master (forced push).

**Comment by prdt3e** [comment]
I will test the next days.
Should I test that in Typo3 9.5?

**Comment by muh-nr** [comment]
No, so far only T3 8.

**Comment by wini2** [comment]
@muh-nr 
thanks for your hint. the output is

array(9) { ["wrap"]=> string(1) "|" ["width"]=> string(5) "1200m" ["height"]=> string(4) "800m" ["crop."]=> array(1) { ["data"]=> string(17) "file:current:crop" } ["JSwindow"]=> string(1) "0" ["JSwindow."]=> array(2) { ["newWindow"]=> string(1) "0" ["if."]=> array(1) { ["isFalse"]=> string(1) "0" } } ["directImageLink"]=> string(1) "1" ["linkParams."]=> array(1) { ["ATagParams."]=> array(2) { ["stdWrap."]=> array(2) { ["cObject"]=> string(3) "COA" ["cObject."]=> array(4) { [98]=> string(4) "TEXT" ["98."]=> array(4) { ["data"]=> string(46) "file:current:description // file:current:title" ["stdWrap."]=> array(1) { ["htmlSpecialChars"]=> string(1) "1" } ["wrap"]=> string(16) "data-caption="|"" ["required"]=> string(1) "1" } [99]=> string(4) "TEXT" ["99."]=> array(4) { ["data"]=> string(18) "file:current:title" ["stdWrap."]=> array(1) { ["htmlSpecialChars"]=> string(1) "1" } ["wrap"]=> string(9) "title="|"" ["required"]=> string(1) "1" } } } ["dataWrap"]=> string(133) "class="lightbox" title="{file:current:title}" rel="lightbox[{file:current:uid_foreign}]" data-fancybox="{file:current:uid_foreign}"" } } ["enable"]=> string(1) "1" } array(10) { ["alt"]=> string(17) "Alternativer Text" ["data-htmlarea-file-table"]=> string(8) "sys_file" ["data-htmlarea-file-uid"]=> string(2) "87" ["data-htmlarea-zoom"]=> string(4) "true" ["height"]=> string(3) "400" ["src"]=> string(65) "fileadmin/_processed_/9/9/csm_450px-HungarianFalls_48496f48c3.jpg" ["style"]=> string(0) "" ["title"]=> string(18) "Titel Beschreibung" ["width"]=> string(3) "300" ["allParams"]=> string(246) "alt="Alternativer Text" data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="87" data-htmlarea-zoom="true" height="400" src="fileadmin/_processed_/9/9/csm_450px-HungarianFalls_48496f48c3.jpg" style="" title="Titel Beschreibung" width="300"" }

**Comment by wini2** [comment]
my ts-setup is

lib.contentElement.settings.media.popup.enable = 1
lib.contentElement.settings.media.popup.directImageLink = 1
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{file:current:uid_foreign}]"   data-fancybox="{file:current:uid_foreign}"  

as you cab see i use fancybox-lightbox.

changing it to
lib.contentElement.settings.media.popup.enable = 1
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"
lib.contentElement.settings.media.popup.JSwindow = 0

with also adding 
$config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
$config['enable'] = 1;
$config['linkParams.']['ATagParams']= 'title="'.$imageAttributes['title'] ?: $file->getProperty('title').'" ';
$GLOBALS['TSFE']->cObj->setCurrentFile($file);

won't help.

**Comment by prdt3e** [comment]
Do you have after $GLOBALS['TSFE']->cObj->setCurrentFile($file); this return-code:
return $this->cObj->imageLinkWrap($img, $file,$config); 

Alternative you can test the new Version. muh-nr has fixed the problem.

**Comment by wini2** [comment]
adding return $this->cObj->imageLinkWrap($img, $file,$config); or using the code from https://github.com/netresearch/t3x-rte_ckeditor_image/blob/master/Classes/Controller/ImageRenderingController.php don't help (cache cleared, processed files deleted).

**Comment by prdt3e** [comment]
Okay, the problem is wrap of the atag:
linkParams.ATagParams.stdWrap.cObject ......

@wini2 
do you use t3sbootstrap?

**Comment by wini2** [comment]
@prdt3e 

yes, i use t3sbootstrap

**Comment by prdt3e** [comment]
1. 
JSwindow does not need to be disabled when I change linkParams, which is handled in fluid_styled_content as well.
Enlarge is made via Constants styles.content.textmedia.linkWrap.lightboxEnabled = 1.
If this is not active, popup will be used automatically.
If no fluid_styled_content is included, no popup is configured and the link should still be generated as href.

[Fluid_Styled_Content Typoscript](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Helper/ContentElement.typoscript)

It is not mandatory for readme?

2. $confi ['enable'] = 1; should always be set. Set via PHP.
[Typo3 Click Enlarge Core](https://github.com/TYPO3-CMS/fluid_styled_content/blob/master/Classes/ViewHelpers/Link/ClickEnlargeViewHelper.php)
(is in the core too)
So we remove sources of errors.
If you put it with php you can take it from the readme.

3.
I looked at the typoscript of wini2. I found a installation with t3sbootstrap.
First, I found a bug
setCurrentFile runs on $ GLOBALS ['TSFE']->cObj, but returns
return $ this->cObj must also return return $ GLOBALS ['TSFE'] -> cObj
-> see [Typo3 Click Enlarge Core](https://github.com/TYPO3-CMS/fluid_styled_content/blob/master/Classes/ViewHelpers/Link/ClickEnlargeViewHelper.php)
Line 130 return $GLOBALS ['TSFE']->cObj->imageLinkWrap not $this

Then {file: current: property} works in the configurations-typoscript for imageLinkWrap.
But that brings us even further, since it's propertiesOfFileReference.
But we need our title.

Our approach was stupid to replace {file: current: title}. 
it is much better if we set file:current:title.
In line 93 we get the FileObject.
We just manipulate the FileObject?
$file->propertiesOfFileReference->title = ?
@muh-nr you have any idea?

**Comment by prdt3e** [comment]
I found a solution !!!
it's easy :laughing: 

`
$config = $GLOBALS['TSFE']->tmpl->setup['lib.']['contentElement.']['settings.']['media.']['popup.'];
$config['enable'] = 1;

$file->_updateMetaDataProperties(array("title"=>($imageAttributes['title']) ? $imageAttributes['title'] : $file->getProperty('title')));
$GLOBALS['TSFE']->cObj->setCurrentFile($file);
return $GLOBALS['TSFE']->cObj->imageLinkWrap(
	$img,
	$file,
	$config
);
`
@muh-nr you can do that nicely now :)

Thanks to all!

**Comment by muh-nr** [comment]
Great, I'm gonna try soon.
I didn't find the replacement method that bad, if someone adds more than just the placeholder, but your solution is quite cleaner.

Thanks man!

**Comment by muh-nr** [comment]
@prdt3e 
What about the `{register:content_uid}`?

**Comment by prdt3e** [comment]
this works via Typoscript.
```php
lib.contentElement.variables.10 = LOAD_REGISTER
lib.contentElement.variables.10.content_uid = TEXT
lib.contentElement.variables.10.content_uid.field = uid
lib.contentElement.settings.media.popup.linkParams.ATagParams.dataWrap = class="lightbox" title="{file:current:title}" rel="lightbox[{register:content_uid}]"
lib.contentElement.stdWrap.append = RESTORE_REGISTER
```

wini2 code code was similar to this: 
```php
lib.contentElement.settings.media.popup{
  directImageLink = 1
  linkParams.ATagParams.stdWrap.cObject = COA
  linkParams.ATagParams.stdWrap.cObject {
    10 = TEXT
    10.value = class="gallery"
    20 = TEXT
    20.field = uid
    20.noTrimWrap = | data-rel="gallery|"|
    30 = TEXT
    30.data = file:current:title
    30.htmlSpecialChars = 1
    30.noTrimWrap = | data-original-title="|"|
  }
  linkParams.ATagParams.dataWrap >
}
```
This is best not to touch, because there are 1000 variants that we can not replace all.
As you can see a stdWrap in ATagParams and there are numerous typoscript commands (prepend,append...) to manipulate this and we should keep that **freedom**.

Do you have read with $config['enable'] = 1;?
So we remove sources of errors.

**Comment by muh-nr** [comment]
Ok, I didn't use that TS way. Good to know and good to have it documented here.
And yes, I'm going to add the enabling again.

**Comment by muh-nr** [comment]
Done.
Please check the current master (commit [d9a902d](https://github.com/netresearch/t3x-rte_ckeditor_image/commit/d9a902d).

**Comment by prdt3e** [comment]
Hmmm.
There are many that use extensions like bootstrap_package or like wini2 t3sbootstrap.
This is not necessary here.

Only as an aside constants if usw fluid_styled_content.
The rest is up to you.
No Typoscript-Code. This is already installed in fluid_styled_content.

The code above with register was just a worakround for typo3 8.7.1 - 8.7.5

**Comment by prdt3e** [comment]
You have write 'title'=>$imageAttributes['title'].
This is not correct. 
Because if $imageAttributes['title'] empty? And the Editor change the title in filelist?
The priority may only be overwritten if there is also a title to overwrite.

**Comment by prdt3e** [comment]
Then we have it :)
Should we then close or leave open?

**Comment by muh-nr** [comment]
Done.
Thanks a lot for helping!
