### ISSUE TITLE
Embedded images (data:image) are not displayed in RTE

### ISSUE THREAD

**Issue by sypets** [netresearch/t3x-rte_ckeditor_image#228]
**Bug description**
Related to #226, will also be handled with PR: #227

Embedded images (starting with "data:image") are not displayed in RTE.

**Steps to reproduce**
To reproduce the problem:

1. copy-paste an image into RTE (e.g. create in Gimp, select all, copy). Result: Image is displayed in RTE
2. save
3. check if image is displayed in RTE: it is not

The reason is not the saving to DB but the loading from DB. (You can cross check the DB entry).

**Expected behavior**

If the embedding of images is not prevented entirely (by some other measure), the image should be displayed. Right now, the behaviour when using rte_ckeditor_image is inconsistent. The image is saved to DB, but is not rendered correctly (see #226) and is not displayed in RTE (see this issue)

**Screenshots or logs**

After copy-pasting:

![image](https://user-images.githubusercontent.com/13206455/227179825-1d18586c-1c48-4e56-bfcc-ac47c229ed05.png)

After saving:

![image](https://user-images.githubusercontent.com/13206455/227180011-826f64a9-4e5a-424a-b35d-e164dff78b38.png)

**Code**

 Netresearch\RteCKEditorImage\Database\RteImagesDbHook::transformTextForRichTextEditor

**Environment**
 - TYPO3 version: 11.5.25
 - PHP version: 8.1
 - Extension version: master

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

**Core behaviour**

I tested the behaviour with only the core (v11): Here, the image is removed on save

**Additional information**

* Wikipedia: data URI scheme: https://en.wikipedia.org/wiki/Data_URI_scheme#Web_browser_support

**Comment by thommyhh** [comment]
If someone comes across this problem with TYPO3 CMS 12 or newer and rte_ckeditor_image 12 or newer, the problem might be another:

It seems that the data filter, which is included in the GeneralHtmlSupport plugin, strips the `src="data:image/..."` from the `<img>`. To allow the base64 encoded data URL, set the following config for CKEditor, to allow all values for the `src` attribute.

```yaml
editor:
   config:
      htmlSupport:
         allow:
            - name: img
              attributes:
                 src: true
```

**Comment by sypets** [comment]
My 2c: I would reconsider allowing data:image images in RTE. It bloats up the database and in my experience it is often used as a convenient shortcut but is not used only for cases where it makes sense.

In v12 the changes in RTE result in these images being removed if the record is saved. I would recommend to convert them before updating.
