### ISSUE TITLE
Wrong image path after saving

### ISSUE THREAD

**Issue by mschmitz89** [netresearch/t3x-rte_ckeditor_image#23]
I'm using latest TYPO3 8.7.9 and latest version of rte_ckeditor_image 8.7.4.

When inserting an image, everything works fine. But after saving the content element, the path to the image is wrong.

Before saving:
`<img data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="93" height="151" src="../fileadmin/user_upload/00fde30303.jpg" width="279" />`
After saving:
`<img data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="93" height="151" src="http://domain.de/web/../fileadmin/user_upload/00fde30303.jpg" width="279" />`

When I change line 41 in typ3image.js from
                            `src: '../' + img.processed.url,`
to
                           ` src: '/' + img.processed.url,`
it works. 

PS: When using the function clickenlarge, it is neccesary to add these lines to the Setup-TS: lib.contentElement.settings.media.popup.enable = 1
Maybe this can be added to the documentation?

All the best
Michael

**Comment by copitz** [comment]
Hi Michael,

thank you. I'm not sure where the absolute url is being added and I'd prefer to find that out first. Are you using config.absRefPrefix?

Regarding the setup docs: sure, could you do a PR?

Cheers, Christian

**Comment by mschmitz89** [comment]
Hi Christian,

thank you very much for your fast reply! 

config.absRefPrefix was a good hint. I set it wrong, because my TYPO3-Installation is located in a subfolder. So everything is fine and the issue can be closed.

PR for docu is done.

Thank you very much!

All the best
Michael

**Comment by copitz** [comment]
You're welcome
