### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by sypets** [netresearch/t3x-rte_ckeditor_image#230]
**Bug description**
When packaging the extension or installing from Composer, some files should be excluded which are not necessary for production and should not exist on the production system. These include for example:

* .github files
* configuation files for development, such as phpstan.neon
* ..

To achieve this a .gitattributes file can be added with the following content:

```
/phpstan.neon  export-ignore
...

```
see https://github.com/TYPO3-Documentation/tea/blob/main/.gitattributes for an example

**Comment by Gitsko** [comment]
@sypets, good idea, thanks for your effort ! 👍
