### ISSUE TITLE
Updated processed images are not used 

### ISSUE THREAD

**Issue by hannesbochmann** [netresearch/t3x-rte_ckeditor_image#232]
**Bug description**
We have RTE fields which contain images with a src like "fileadmin/_processed_/9/f/csm_image_b87be79882.png". If the image got updated meanwhile and for example the modification date changed, the newly processed file will have a new path as the checksum changes. But this new path is not used if the src attribute doesn't start with a slash.

**Steps to reproduce**
To reproduce the problem:

- create content element with a image in RTE
- make sure the src attribute doesn't start with a slash
- update image through filelist for example by exchanging the file
- remove processed file (e.g. fileadmin/_processed_/9/f/csm_image_b87be79882.png)
- reload page in FE
- TYPO3 will create a new processed file but ImageRenderingController will return the old deleted processd file leading to a brokem image tag

**Expected behavior**
ImageRenderingController should return the newly processed file.

**Environment**
 - TYPO3 version: 11.5
 - PHP version: 8.0
 - Extension version: 11.0.9

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

The problem is caused by the last changes from #197 when the leading slash is added if only a path is given and the file object has another public URL than the src attribute. In this case $imageSource variable needs to be updated with the URL of the newly processed file or the initial src attribute is used. I will provide a PR.

**Comment by Gitsko** [comment]
The problem should be fixed with version 11.0.14 #233.
