### ISSUE TITLE
Creation of dynamic property Netresearch\RteCKEditorImage\Database\RteImagesDbHook::$pObj is deprecated

### ISSUE THREAD

**Issue by kevin-appelt** [netresearch/t3x-rte_ckeditor_image#235]
**Bug description**
PHP Runtime Deprecation Notice: Creation of dynamic property Netresearch\RteCKEditorImage\Database\RteImagesDbHook::$pObj is deprecated and throws an exception when opening something that contains an RTE in backend.

**Expected behavior**
Calling the RTE in backend should work.

**Environment**
 - TYPO3 version: 11.5.27
 - PHP version: 8.2.3
 - Extension version: 11.0.9

**Comment by loeru23** [comment]
The warning is telling you that there is a property you are trying to set which isn't listed at the top of the class.
To fix the problem you will need to declare them explicitly:

```
class RteImagesDbHook extends RteHtmlParser
{
    public $pObj;
    public $transformationKey;

    ...
}
```

**Comment by IngoMueller** [comment]
Hey Together,

I just stumbled into the same error and wanted to ask if a merge and release are planned here.

best regards
Ingo
