### ISSUE TITLE
Call to a member function count() on null

### ISSUE THREAD

**Issue by fbatschi** [netresearch/t3x-rte_ckeditor_image#242]
**Bug description**
After updating our TYPO3 installation to the latest 11.5.29 version and while using rte_ckeditor_image 11.0.11 I get the  error  

```
Error
Call to a member function count() on null
in /var/www/typo3/public/typo3conf/ext/rte_ckeditor_image/Classes/Backend/Preview/RteImagePreviewRenderer.php line 129
```

regardless of which page i try to edit.

The line is this

https://github.com/netresearch/t3x-rte_ckeditor_image/blob/f78ae0e95be2a30e3d03fbc7db7449c2a443b0ea/Classes/Backend/Preview/RteImagePreviewRenderer.php#L129

**Expected behavior**

No error is thrown.

**Possible Fix**

Chaging the line to

```
if (isset($node->childNodes) && $node->childNodes->count() > 0) {
```

fixes this.

**Environment**
 - TYPO3 version: 11.5.29
 - PHP version: 7.4
 - Extension version: 11.0.11

**Documentation**
Have you checked the readme/documentation?
- [X] Yes, but I couldn't find anything helpful

**Comment by kkugelmann** [comment]
Same problem in one of our clients instances:
TYPO3 version: 11.5.29
PHP Version: 7.4.3
Extension versions: 11.0.11

**Comment by npoggenburg** [comment]
Can confirm:
TYPO3 version: 11.5.30
PHP Version: 7.4.3
Extension versions: 11.0.11
