### ISSUE TITLE
No warning before referenced image is deleted (softref not working correctly?)

### ISSUE THREAD

**Issue by biedert** [netresearch/t3x-rte_ckeditor_image#243]
**Question**
Maybe I misunderstood the purpose of the RteImageSoftReferenceParser, but my expectation would be to get a warning when I try to delete an image which is referenced in a tt_content element with an image reference in the bodytext field. At least in my fresh installation of TYPO3 11.5 with rte_ckeditor_image installed, this is not the case. Am I missing something here?

**Environment**
 - TYPO3 version: 11.5.13
 - PHP version: 8.0
 - Extension version: 11.0.11

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

**Comment by Patta** [comment]
I can confirm, that image reference is not working anymore. counter is 0. a warning log i written:
`Tue, 22 Aug 2023 14:20:12 +0200 [WARNING] request="0487ed6f1fbbe" component="TYPO3.CMS.Core.DataHandling.SoftReference.SoftReferenceParserFactory": No soft reference parser exists for the key "images". - {"parserKey":"images"}`

**Comment by magicsunday** [comment]
After adding an image in the RTE editor and saving it:
![grafik](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/564393/fb8ef5d8-fbca-4ace-8c75-06e49d7319bc)
![grafik](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/564393/10165d65-5ed3-4637-86cf-4a34b38a369f)

a new entry should appear in the "sys_refindex" table. To do this, filter the “softref_key” column for “rtehtmlarea_images”.
![grafik](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/564393/0f058d11-5b33-40a3-9733-7048624c91eb)

When I try to delete the image via the backend, I get the following warning.
![grafik](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/564393/70fc4587-6c6b-42fe-b8ce-df3ec9bc6e2c)

**Comment by Gitsko** [comment]
@biedert. @Patta can you please check if the problem still exists with the current version ? (v11.014)

**Comment by sypets** [comment]
After saving an element, the reference index should be updated automatically. You can check this by

1. Looking in the file list - in the right column, the number of references is displayed und you can also click on it to get details

![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/13206455/7a90e15f-1d4e-4e9a-8f6b-f17934a10322)


2.  (or) check table `sys_refindex`

I have noticed 2 problems so far with images inserted with rte_ckeditor_image and references:

1. Saving the reference index did not always work. **I think this should be fixed**, not sure. (I am using a patched version, which works in TYPO3 v11). Ideally test with latest release!
2. If you are using images in other RTE fields besides tt_content.bodytext: The softref parser 'rtehtmlarea_images' **must** be added to the softref field in the TCA for all affected fields. (If the fields are enabling images to be inserted depends on your RTE configuration, so only necessary to do this where you need it). **This is up to you to configure, it will not work out of the box!** If you do not do this, the references will not be saved AFAIK.

e.g. 
`Configuration/TCA/Overrides/tx_news_domain_model_news.php:`

```
$softref = explode(',', $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['bodytext']['config']['softref'] ?? '');
    if (!in_array('rtehtmlarea_images', $softref, true)) {
        $softref[] = 'rtehtmlarea_images';
        $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['bodytext']['config']['softref'] = implode(',', $softref);
    }

```

You can also compare [Configuration/TCA/Overrides/tt_content](https://github.com/netresearch/t3x-rte_ckeditor_image/blob/9a578b5bcbe3deb8cac5280257c01210d76194da/Configuration/TCA/Overrides/tt_content.php#L20)  in rte_ckeditor_image.

----

If you have the possibility to debug, try setting a breakpoint in `RteImageSoftReferenceParser::parse` and `findImageTags`


----

Related issue: https://github.com/netresearch/t3x-rte_ckeditor_image/issues/45
