### ISSUE TITLE
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function count() on null 

### ISSUE THREAD

**Issue by olegkarun** [netresearch/t3x-rte_ckeditor_image#248]
**Bug description**
PHP error

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function count() on null \| Error thrown in file /var/www/www.eybwallwitz.de/releases/eub_typo3/public/typo3conf/ext/rte_ckeditor_image/Classes/Backend/Preview/RteImagePreviewRenderer.php in line 129. Requested URL: 

**Steps to reproduce**
To reproduce the problem:

1. Add any text element 
2. Add image as rte_ckeditor_image
3. Add This element in ant b13/container

**Expected behavior**
Render Elements preview without error

**Screenshots or logs**
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/3882942/14b0fea9-d6d6-42fa-90e0-42b623071c43)

**Environment**
 - TYPO3 version: 11.5.30
 - PHP version: 7.4.3
 - Extension version: 11.0.11
 - 
**Documentation**
Have you checked the readme/documentation?
- [ ] Yes, but I couldn't find anything helpful

**Comment by magicsunday** [comment]
Should be fixed in 11.0.12
