### ISSUE TITLE
netresearch/rte-ckeditor-image auf php 8.2

### ISSUE THREAD

**Issue by fulaizhang** [netresearch/t3x-rte_ckeditor_image#249]
**Bug description**
Probem with PHP 8.2

**Steps to reproduce**
To reproduce the problem:

1. backend "Create new content element" -> "Text & Media"

**Expected behavior**
What is the expected behavior?

![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/53898514/340e242d-debc-4f2a-93c9-9239538462b3)

**Environment**
 - TYPO3 version: 11.5.31
 - PHP version: 8.2
 - Extension version: 11.0.11

**Comment by magicsunday** [comment]
This is already fixed in current master.

**Comment by magicsunday** [comment]
Please try new release 11.0.12
