### ISSUE TITLE
Rte image preview broken since v11.0.12

### ISSUE THREAD

**Issue by Patta** [netresearch/t3x-rte_ckeditor_image#251]
**Bug description**
Since v11.0.12 the backend rte image preview is not working anymore. The preview only shows just html/code of the image.

**Steps to reproduce**
To reproduce the problem:

1. Setup
2. Add image to rte
3. Look at page with web module

**Expected behavior**
Preview of rte image

**Screenshots or logs**

Should:
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/2151127/ccd4a0ba-cb8d-4a2c-ba3a-2533f10fcfd8)

Is:
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/2151127/06201e0c-1fad-4a65-a2e3-57719fda2a5d)

**Workaround:**
revert commit https://github.com/netresearch/t3x-rte_ckeditor_image/commit/9fb0b0e68c825c1d480da194b8b86300ac8dac79

**Environment**
 - TYPO3 version: 11.5.31
 - PHP version: 8.1.23
 - Extension version: 11.0.12

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

**Comment by Patta** [comment]
Additional, the commit https://github.com/netresearch/t3x-rte_ckeditor_image/commit/9fb0b0e68c825c1d480da194b8b86300ac8dac79 breaks all other content element previews.

Is: Text element is with v11.0.12:
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/2151127/19eb33b5-bc10-45b5-9cc5-9e2dcde6dd36)

Should: Text element with v11.0.11:
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/2151127/db423b04-00c1-492e-836e-8d38b7f030c0)

**Comment by magicsunday** [comment]
Hi, could you please check if branch https://github.com/netresearch/t3x-rte_ckeditor_image/tree/GH-244 fixes your problems?

**Comment by Patta** [comment]
@magicsunday the changes in https://github.com/netresearch/t3x-rte_ckeditor_image/commit/908d149cdf89601743215a39f365367eca48d0ff fixes this issues, yes.
Maybe you could use the https://github.com/TYPO3/html-sanitizer for that.

**Comment by magicsunday** [comment]
New release 11.0.13 created.
