### ISSUE TITLE
Exception thrown when element has deleted file references

### ISSUE THREAD

**Issue by hannesbochmann** [netresearch/t3x-rte_ckeditor_image#254]
**Bug description**
When a element (e.g. tt_content) with a RTE is opened in the BE a exception is thrown.

**Steps to reproduce**
To reproduce the problem:

1. Create a text element and link to a file in the RTE.
2. Delete said file
3. Open the text element in the BE

**Expected behavior**
The RTE renders normal and the missing image is simply excluded.

**Screenshots or logs**
TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException, code #1317178604, file /var/www/htdocs/typo3/sysext/core/Classes/Resource/ResourceFactory.php, line 223: No file found for given UID: xxx

This error occurs since version 11.0.14 and was introduced with the changes for #199 

**Environment**
 - TYPO3 version: 11.5.32
 - PHP version: 8.0
 - Extension version: 11.0.14

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

**Comment by Gitsko** [comment]
Hi @hannesbochmann,

i have moved your change to the TYPO3 v11 branch and added a logger, thanks for your efforts. Exception handling already exists for TYPO3 v12.

**Comment by hannesbochmann** [comment]
@Gitsko Thanks for merging.
