### ISSUE TITLE
Default options in TSconfig

### ISSUE THREAD

**Issue by agendartobias** [netresearch/t3x-rte_ckeditor_image#258]
Hey, is it possible to change default settings for this attributes: "Enlarge on Click", "Alternative Text - Set element specific value - so checkbox is unchecked" ?

Similar as:
`
RTE.default {
    buttons.image.options.magic {
        maxWidth = 1920
        maxHeight = 1280
    }
}
`

**Comment by Gitsko** [comment]
Unfortunately this will not be possible, the MaximumWidth and MaximumHeight is used in the MagicImageService and can therefore be predefined, for the other options I currently see no way to set defaults. :(
