### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by Tomowok** [netresearch/t3x-rte_ckeditor_image#268]
With TYPO3 v12, it's not possible anymore to use aligment on images.
Maybe with wrapping a `<p>` arround the `<img>` tag ?

Or did i miss a config ?

**Environment**
 - TYPO3 version: 12.4.10
 - PHP version: 8.1
 - Extension version: 12.0.0

**Comment by Gitsko** [comment]
Hi @Tomowok ,

with the current version 12.0.2 a <p> tag is now rendered around the image, so it can be aligned again.

**Comment by Tomowok** [comment]
Thanks.
