### ISSUE TITLE
Regression: "Call to a member function count() on null"

### ISSUE THREAD

**Issue by rvock** [netresearch/t3x-rte_ckeditor_image#270]
**Bug description**
When opening the page view of a page, you sometimes get the error "Call to a member function count() on null".

**Steps to reproduce**
1. Update from 11.0.14 to v11.0.15
2. Open the page view for a page

<img width="976" alt="Exception" src="https://github.com/netresearch/t3x-rte_ckeditor_image/assets/209159/ae8bc200-75a2-48f1-9cd5-dd52d8b42568">

The regression was introduced with https://github.com/netresearch/t3x-rte_ckeditor_image/commit/34bd1ae125ed56c98cb8cbe639b387d4778ed811

**Comment by m-huether** [comment]
It seems that the bugfix "($node->childNodes !== null) && ..." from previous versions has disappeared in v11.0.15.

**Comment by CybotTM** [comment]
According to https://github.com/netresearch/t3x-rte_ckeditor_image/commit/34bd1ae125ed56c98cb8cbe639b387d4778ed811

This is due to an outdated PHP version.
