### ISSUE TITLE
Inline Images

### ISSUE THREAD

**Issue by dimitri-koenig** [netresearch/t3x-rte_ckeditor_image#274]
Hi guys

I have a case where images should be placed within a paragraph. But that does not work.
Even raw bodytext data like `<p>... <img... />...</p>` is transformed to `<p>...</p><img... /><p>...</p>` in the RTE and in the frontend to `<p>...</p> <p><img... /></p> <p>...</p>`

Any idea on how to change that? Is that a config issue or a bug?

**Comment by CybotTM** [comment]
Hi @dimitri-koenig,

what's your extension and TYPO3 version?

**Comment by dimitri-koenig** [comment]
Extension Version is 12.0.1
TYPO3 Version is 12.4.12

**Comment by dimitri-koenig** [comment]
I found a possible solution: Change add $block to allowIn config in typo3image.js:430
Now i need to check some other contents to see wether it really fits every case

**Comment by wwenzel** [comment]
I don't understand this solution proposal.
I have made this discribed change in typo3image.js:430 but there is no affect visible.
When i add an image inside the RTE, the exisiting paragaph is still split into two paragraphs and the new img tag is added outside.

Is any further change necessary?

Any help or hint is welcome.

Thanks.

**Comment by dimitri-koenig** [comment]
With this change the inline image is not placed within its own p tag but inside the same block as the rest of the text. If you don't see any visible changes then you probably have set images as block via css rather than inline-block.

**Comment by wwenzel** [comment]
Hm, with no "visible changes" i meant, no changes in the resulting source code, neither in the RTE nor in the rendered frontend page.
It is still like <p>... <img... />...</p> is transformed to <p>...</p><img... /><p>...</p> in the RTE and in the frontend to <p>...</p> <p class="image"><img... /></p> <p>...</p>

**Comment by wwenzel** [comment]
The reason why it doesn't work for me was the usage of the old version of TYPO3 V12.4.9.
With the update to V12.4.14 this bugfix in typo3image.js:430 works fine for me, too.

I'm sorry for this confusion.

**Comment by dimitri-koenig** [comment]
Nice, so that means you can merge this fix? 👍

**Comment by wwenzel** [comment]
Sorry, but i think i've not enough rights to do this job.in #276

**Comment by lucmuller** [comment]
Up ! +1 on this topic !

**Comment by Gitsko** [comment]
Sry for the delay.
