### ISSUE TITLE
TYPO3 9.3

### ISSUE THREAD

**Issue by DavidBruchmann** [netresearch/t3x-rte_ckeditor_image#28]
Is there any update for TYPO3 9.3 in the pipe?

**Comment by prdt3e** [comment]
I have solved the error:
SelectImageController.php
` public function mainAction(ServerRequestInterface $request): ResponseInterface
    {
        return $this->isInfoAction
            ? $this->infoAction($request, $response)
            : parent::mainAction($request, $response);
    }`

Now there are bugs in JavaScript, who can help?

**Comment by prdt3e** [comment]
My Fork for 9.5.1:  https://github.com/prdt3e/t3x-rte_ckeditor_image

**Comment by celmedia** [comment]
workes fine with 9.5.1 thanks alot

**Comment by stephangrass** [comment]
The fork from prdt3e will work with 9.5.1 on Chrome, Firefox and Safari.
Thanks!

**Comment by szykuc** [comment]
> My Fork for 9.5.1: https://github.com/prdt3e/t3x-rte_ckeditor_image

I'm testing your fork on 9.5.1 and i have some problem:

`/typo3/sysext/recordlist/Resources/Public/JavaScript/ElementBrowser.js?bust=281c9eb4f39842a51ebd50dca51d6236359c9a3c:79 Uncaught TypeError: Cannot read property 'apply' of undefined`

**Comment by prdt3e** [comment]
Can you test this Pull-Request: https://github.com/netresearch/t3x-rte_ckeditor_image/pull/33

Thanks

**Comment by szykuc** [comment]
Still the same error

**Comment by szykuc** [comment]
Now i notice that yours fork works well on firefox (in chrome same error) but thommyhh pull not, even in ff

**Comment by prdt3e** [comment]
In which browser version does the error occur? 
I'll check it out this weekend if I can reproduce the error.

**Comment by szykuc** [comment]
Chrome 70.0.3538.77

**Comment by prdt3e** [comment]
Works fine on Chrome Version 70.0.3538.110 (Windows 7 / 10)
Whats your OS?

**Comment by muh-nr** [comment]
Sorry @prdt3e, forgot your fork.
What do you think, should we use some of your changes?
Just contact me (MatMan) in #ckeditor-integration T3 slack channel.

**Comment by prdt3e** [comment]
All good.
The JavaScript from thommy is better.
I wrote you in slack.

**Comment by muh-nr** [comment]
Please check branch **[dev-TYPO3_9.x](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-TYPO3_9.x) for TYPO3 9 support** and post your experiences in this issue here. Thanks.
