### ISSUE TITLE
click-enlarge not working (no different rendering)

### ISSUE THREAD

**Issue by shuffgy** [netresearch/t3x-rte_ckeditor_image#29]
So i'm importing an image and it renders 

`<p><img data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="201" data-htmlarea-zoom="true" height="574" src="../fileadmin/_processed_/5/e/csm_bg_location_f9014553ff.jpg" width="1020" /></p>`

After saving the element, it will render it to: 

`<p><img alt="" height="574" src="https://heinekingmedia.de/../fileadmin/_processed_/5/e/csm_bg_location_f9014553ff.jpg" width="1020" /></p>`

So there are no informations anymore to use any lightbox or even a simple <a>-Tag to open the image full-size in a new tab.

Am I missing something? I read some threads here already but nothing helped.

TYPO3: 8.7.17
rte_ckeditor_image: 8.7.4

**Comment by prdt3e** [comment]
@shuffgy 
do you have set an absRefPrefix for subfolder? 
../ is not ordinary.
Have you a other file-storage?

**Comment by prdt3e** [comment]
@muh-nr 
I think it's safer in SelectImageController.php (104) not to pass the "getPublicUrl" here, but to prepare it in PHP.
Have a look at /typo3/sysext/core/Classes/Html/RteHtmlParser.php (502).
TS_images_rte will also run after saving.
This way prevent the conversion and we exclude sources of error.

**Comment by prdt3e** [comment]
@muh-nr 
```php 
$src = $processedFile->getPublicUrl()
$siteUrl = GeneralUtility::getIndpEnv('TYPO3_SITE_URL');
$sitePath = str_replace(GeneralUtility::getIndpEnv('TYPO3_REQUEST_HOST'), '', $siteUrl);
$absoluteUrl = trim($src);
 if (strtolower(substr($absoluteUrl, 0, 4)) !== 'http') {
       $src = preg_replace('#^' . preg_quote($sitePath, '#') . '#', '', $src);
       $src = $siteUrl . $src;
}
```

**Comment by muh-nr** [comment]
@prdt3e 
I implemented your approach for securely rendering the img src in branch [dev-#29-secure-img-src](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-%2329-secure-img-src).

But I wonder how the `../` comes into the renderer, I never found it anywhere. 
Any idea?

**Comment by prdt3e** [comment]
rte_ckeditor_image/Resources/Public/JavaScript/Plugins/typo3image.js Line 40 :)

**Comment by prdt3e** [comment]
:D nooo! 
You built that into the wrong controller :D
SelectImageController.php Line 100.

It's about the backend.
After selecting an image in the backend, SelectImageController.php is executed via Ajax.
This provides the echo (94) to the javascript which inserts the image in the chkeditor.
Currently this is inserted with ../ because we are in the backend. And this ../ makes seemingly often mistakes here.
After saving in the backend, this is then converted to the URL, but apparently not always. That's why we set it right.

You can immediately consider thommy's changes here for 9.5.
```php 
use TYPO3\CMS\Core\Http\JsonResponse;
return new JsonResponse([

]);
```

**Comment by prdt3e** [comment]
Please undo frontend again. Here to adjust the URLs would be too hot with multidomain, absRefPrefix, baseURL

**Comment by prdt3e** [comment]
If you select a picture from the file list
You can show in your browsernetwork for calls ?route=%2Frte%2Fwizard%2Fselectimage...
Press Right open Link in new tab. 
But you already know that.

**Comment by prdt3e** [comment]
remove ../ in JavaScript.
rte_ckeditor_image/Resources/Public/JavaScript/Plugins/typo3image.js Line 41

**Comment by muh-nr** [comment]
Merged fix into master.
