### ISSUE TITLE
I think the package name 'cms_rte_ckeditor' in https://github.com/netresearch/t3x-rte_ckeditor_image/blob/main/ext_emconf.php is wrong! Please fix it!

### ISSUE THREAD

**Issue by hdietrich-timespin** [netresearch/t3x-rte_ckeditor_image#292]
Proplem since Version: t3x-rte_ckeditor_image 12.0.1

I think the package name 'cms_rte_ckeditor' in https://github.com/netresearch/t3x-rte_ckeditor_image/blob/main/ext_emconf.php is wrong:

Typo3 12.4.17 throw an exception in Backend, that cms_rte_ckeditor is unknown!  

'cms_rte_ckeditor' => '12.4.0-12.4.99',

This commit is the problem:
https://github.com/netresearch/t3x-rte_ckeditor_image/commit/5cff197dc2ff81f8b45e69b22815f944b2cff3cb

Depend package name must be:

'rte_ckeditor' => '12.4.0-12.4.99',

![grafik](https://github.com/user-attachments/assets/bfbbab3d-5ec0-4897-8554-fdfcc7a7b04c)

![grafik](https://github.com/user-attachments/assets/18b6b618-4da9-46c7-8abc-5c2a9cadbee5)

Please fix it!

**Comment by Gitsko** [comment]
Hi @hdietrich-timespin,

we change the ext_emconf.php and merge into master Branch, can you check if your problem is solved with this change ?

**Comment by hdietrich-timespin** [comment]
Yes, I did that same fix in my typo3 12 and it work! 

Thanks for fix to @Gitsko
