### ISSUE TITLE
Issue with Image properties

### ISSUE THREAD

**Issue by MowWow** [netresearch/t3x-rte_ckeditor_image#3]
Hi,

I'm using TYPO3 8.7.1

When i right click on an image, and then click on Image properties, i always obtain the File selector modal, not the image properties. I'm using the last version of your extension (8.7.1) 

Thanks a lot

**Comment by copitz** [comment]
Hi,

which OS + browser are you using? I can't reproduce this with Win + Chrome

**Comment by MowWow** [comment]
I found the reason. It's a migrated TYPO3, so the images doesn't have the data-htmlarea-file-uid attribute. When the data-htmlarea-file-uid is present it works. I made a script to add the attribute so it works for me now.

Thanks

**Comment by copitz** [comment]
Great - you're welcome :)
