### ISSUE TITLE
ext_emconf.pfp in TER depends on cms_rte_ckeditor

### ISSUE THREAD

**Issue by stephangrass** [netresearch/t3x-rte_ckeditor_image#302]
In the ext_emconf.php file in the TYPO3 Extension Repository (TER), 'cms_rte_ckeditor' is listed under depends instead of 'rte_ckeditor'. As a result, the extension cannot be installed in the usual way.

**Comment by CybotTM** [comment]
Fixed with #280 in release v12.0.3
