### ISSUE TITLE
Plans for Version for TYPO3 13

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#303]
Will there be released a Version for v13? And, if yes, when can I expect it?

**Comment by gmt-it** [comment]
I would be interested in that too.

**Comment by Gitsko** [comment]
hi, 

sry currently there are no concrete plans or preparations for v13, if there are any efforts from the community, please create a merge request.

**Comment by marekskopal** [comment]
I tried to sort out compatibility with v13 in my fork https://github.com/marekskopal/t3x-rte_ckeditor_image . It generally works, but there is one problem I can't solve. 

In TypoScriptFrontendController class the getPagesTSconfig()method has been removed, and I don't know any other way to access TsConfig from a frontend request (tsConfig is only supposed to be used for the backend).

**Comment by gmt-it** [comment]
Hi.

Does this help?
$fullTypoScript = $request->getAttribute('frontend.typoscript')->getSetupArray();

Found it here:
https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/Configuration/TypoScript/PhpApi/Index.html

Best regards

Guido

**Comment by gmt-it** [comment]
I tested it with Typo3 13.4.1. Works partially. See https://github.com/netresearch/t3x-rte_ckeditor_image/issues/309
