### ISSUE TITLE
"Clear processed files" breaks images

### ISSUE THREAD

**Issue by Ceremony64** [netresearch/t3x-rte_ckeditor_image#32]
According to the short text associated with the "Clear process files"-button, all processed images should be recreated upon pagevisit:
> The File Abstraction Layer stores a database record for every file it needs to process. (e.g. image thumbnails) In case you modified some graphics settings (All Configuration [GFX]) and you need all processed files to get regenerated, you can use this tool to remove the existing ones. The new processed files are created **once they are needed**.

However, if you click on said button, all ckeditor images break and won't be regenerated when visiting the page in the frontend. Only by saving the content element again in the backend, it does get regenerated, given the original file (see data-htmlarea-file-uid attribute) still exists.

It would be best if these "magic" images are regenerated upon page request instead of within the backend editor.

Typo3 processes this content already to replace links with the correct paths (e.g. t3://page?uid=1). A similar behavior might be possible to be implemented, reusing the same syntax (e.g. t3://file?uid=123). That way, the original file reference is properly preserved, the processed file and its path gets generated upon request and can still be cached. Somewhat similar to how the f:image viewhelper works, tho I dunno how easy/hard/possible this is. Either way, the current behavior is too destructive.

**Comment by muh-nr** [comment]
@Ceremony64 
Works properly for me in TYPO3 8.7.20
After deleting the images within _processed_ folder, they are regenerated on page visit.
Do you still have this problem?

**Comment by Ceremony64** [comment]
Still broken for me... It only regenerates when I save the content element again, not upon page visit

**Comment by muh-nr** [comment]
@Ceremony64 
Please give us some details:

- TYPO3 version
- extension version
- included static templates (Template TS)
- does it work with default T3 image elements

Thanks

**Comment by Ceremony64** [comment]
Tested it again and now it seems to work... I have no idea what has changed, but it certainly wasn't the recent patches, as I am still on v8.7.4...

I'll close it for now. Once I figure out what has changed/causes it, I'll be back :-)
