### ISSUE TITLE
8.7.7 Call to undefined method DOMNodeList::count() 

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#39]
after update to 8.7.7 (TYPO3 8.7.16) i get the following error-message
Call to undefined method DOMNodeList::count()

**Comment by muh-nr** [comment]
Sorry for that.
Fixed in current master.

**Comment by wini2** [comment]
thanks a lot! 
with your fix it seems to work fine.

**Comment by beath** [comment]
Can confirm this Bug. Downgraded to 8.7.4 to prevent it.

**Comment by prdt3e** [comment]
For old Version: (PHP 7.2)
PHP Warning: DOMDocument::loadHTML(): Empty string supplied as input ImageRenderingController.php line 203

**Comment by sophiaphillyqueen** [comment]
Sorry - - - - what was the fix - - - and until the fix is applied to the system that I have to work with, what work-around can I use?

**Comment by muh-nr** [comment]
Hi @sophiaphillyqueen,
the fix was merged into master a long time ago. You should use branch TYPO3_8.7.x for TYPO3 8 or master for TYPO3 9.
