### ISSUE TITLE
Handle linked images

### ISSUE THREAD

**Issue by muh-nr** [netresearch/t3x-rte_ckeditor_image#42]
Continues the approach of #35.
We need to find a way to render only the images when wrapped into a link.

`tt_content.stdWrap.parseFunc`
or
`lib.parseFunc.tags.img` AND `lib.parseFunc.tags.a`

**Comment by prdt3e** [comment]
@bmack do you have an idea?

**Comment by prdt3e** [comment]
I found contentPostProc-all.
However, I have read it has problems with the cache. 
The solution here: [typo3blogger.de](https://typo3blogger.de/hook-contentpostproc-vs-cache/) 

```php 
public function replaceContent(&$parameters, TypoScriptFrontendController $parentObject)
{
    // Replace Content
    $parameters['pObj']->content = preg_replace(
        $configuration['search.'],
        $configuration['replace.'],
        $parameters['pObj']->content
    );
}
```

Use a regular expression to replace the images with data-htmlarea-file-uid.
Ideas?

**Comment by prdt3e** [comment]
The problem is not the umlauts.
The Problem is "lib.parseFunc.tags.img".
There are no img parsed in external a-tags and we need a workaround for this.

Thank you for your help.

**Comment by muh-nr** [comment]
@prdt3e Thanks for your input.

As DomDocument didn't work as aspected, I refactored to replacement of the images (via regex) with new manually built elements.
Output looks quite clean for me.
Could you please have a look at branches
* TYPO3 v9: `dev-9x-#42-linkedImageRenderer`
* TYPO3 v8: `dev-8x-#42-linkedImageRenderer`

Next step is to move it to `contentPostProc-output` processor.

**Comment by muh-nr** [comment]
@prdt3e Sorry, I don't understand exactly. You want to remove the loadHTML completely? It's not used for the replacement any more, only for detection and handling of the images.

**Comment by prdt3e** [comment]
Yes exactly. At this point one could use the same as a regex (for search ids data-htmlarea-file-uid=) which builds up the array for the foreach.
I think loadHTML with the filter getElementsByTagName needs a lot of performance.

**Comment by muh-nr** [comment]
Ok, agree. I'll refactor this, if the approach is working.
Can anyone test with different configurations / content types etc.?

**Comment by prdt3e** [comment]
I can test it tonight with:
- Textmedia
- Plugin (product-extension with detail text)

**Comment by muh-nr** [comment]
I refactored the link renderer.
We now safely extract the images via regex instead of DomDocument elements.
Please check branches:

* [TYPO3 v9: dev-9x-#42-linkedImageRenderer](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-9x-%2342-linkedImageRenderer)
* [TYPO3 v8: dev-8x-#42-linkedImageRenderer](https://github.com/netresearch/t3x-rte_ckeditor_image/tree/dev-8x-%2342-linkedImageRenderer)

**Comment by prdt3e** [comment]
Like :+1:
