### ISSUE TITLE
Enlarge on Click with "css sytled content" -  does not work

### ISSUE THREAD

**Issue by Gitsko** [netresearch/t3x-rte_ckeditor_image#44]
Hi,

i used "css_styled_content" als rendering engine. 
With this renderer the function "Enlarge on Click" does not work, the image was linked to the original image.

 With "fluid_styled_content" it works.

Can you help me ? 🙋‍♂️

**Comment by prdt3e** [comment]
I think that would have to work. css_styled_content is a few years back :)
TS:
```php
lib.contentElement = COA
lib.contentElement.settings {
    media {
        popup {
            width = {$styles.content.imgtext.linkWrap.width}
            height = {$styles.content.imgtext.linkWrap.height}
            crop.data = file:current:crop
            directImageLink = 1
            linkParams.ATagParams.dataWrap = class="lightbox" rel="{$styles.content.imgtext.linkWrap.lightboxRelAttribute}"
        }
    }
}
```

**Comment by Gitsko** [comment]
I added the TS into the Setup but this doesn't work. :(

**Comment by prdt3e** [comment]
Just contact me in #ckeditor-integration T3 slack channel [(link).](https://my.typo3.org/about-mytypo3org/slack/l)

**Comment by muh-nr** [comment]
@Gitsko 

Enable the default ClickEnlarge function by adding the following TS:
```
lib.contentElement.settings {
    media {
        popup {
            # enable = 1
            JSwindow = 1
        }
    }
}
```

With the following TS you add the necessary lightbox attributes but of course you have to include the lightbox javascript/css yourself:
```
lib.contentElement.settings {
    media {
        popup {
            width = {$styles.content.imgtext.linkWrap.width}
            height = {$styles.content.imgtext.linkWrap.height}
            crop.data = file:current:crop
            directImageLink = 1
            linkParams.ATagParams.dataWrap = class="lightbox" rel="{$styles.content.imgtext.linkWrap.lightboxRelAttribute}"
        }
    }
} 
```

**Comment by Gitsko** [comment]
@muh-nr, great it works 🚀
