### ISSUE TITLE
Reference index not updated

### ISSUE THREAD

**Issue by mbrodala** [netresearch/t3x-rte_ckeditor_image#45]
When embedding an image using this extension, the reference counter for the image is not increased. This is essential to prevent accidental deletes of images embedded via RTE.

**Comment by muh-nr** [comment]
Hi @mbrodala,
thanks for your hint.
Not simple to count it down again after removing an image.

Feel free to add a pull request.

**Comment by muh-nr** [comment]
Sounds good. Would be very nice.

**Comment by muh-nr** [comment]
@mbrodala,
any news on this?

**Comment by mbrodala** [comment]
I was off for vacation in the last 2 weeks. Our fix seems to work fine, I just need some time to turn it into a PR. I try to do this this week.

**Comment by muh-nr** [comment]
Hey @mbrodala, I'm still interested!

**Comment by prdt3e** [comment]
We have to set a filereference after inserting.
In this reference we also have the possibility to save the image relationships:
{ "Default": { "cropArea": ​​{ "x" 0, "y" 0, "width" 1, "height" 1}, "selectedRatio": "NaN", "focus area": ​​null} }
Same title, alternative.

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Fal/UsingFal/ExamplesFileFolder.html#creating-a-file-reference

However, we must be careful not to unnecessarily fill the table.
So you have to delete or change old references again.
This would be a PreSafe (in the Core Hook).

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Html/RteHtmlParser.php (235)

ext_localconf.php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_parsehtml_proc.php']['removeParams_PostProc']['link2language'] = \CMSExperts\Link2language\RteParserTypoLinkHook::class;

removeParams_PostProc is a CMD. 
Unfortunately it does not know what it is for. Maybe a var_dump

**Comment by muh-nr** [comment]
Hi @mbrodala,
I did some cleanups and merged your changes into master via branch issue-45.
Please check the current master.

Thanks for your help!

**Comment by mbrodala** [comment]
Thanks a lot, looking forward to the next release. :-)

**Comment by mbrodala** [comment]
For the reference: 8005c8b55d40dc88a152acd9527d4073f1a0e886

**Comment by prdt3e** [comment]
What if the editor is outside of ['tt_content'] ['columns'] ['bodytext']?
New field? News plugin? Own extension?

**Comment by prdt3e** [comment]
$TYPO3_CONF_VARS['SC_OPTIONS']['GLOBAL']['softRefParser'] ?

**Comment by mbrodala** [comment]
@prdt3e See the related change, you'll need to add a small TCA overrides snippet for your field.

**Comment by prdt3e** [comment]
we should find a universal solution.
That would be an impertinence for every field and for every extension to add.
@mbrodala what do you mean?

**Comment by prdt3e** [comment]
The solution can be found here with a loop.
It would then be all fields in tt_content covered.

https://github.com/FriendsOfTYPO3/rtehtmlarea/blob/master/Configuration/TCA/Overrides/tt_content.php

But I'm not happy.

**Comment by sypets** [comment]
What is the current status on this?

I tested that a sys_refindex entry gets created when inserted an image in an RTE-field (tt_content.bodytext). This is the case for 9.0.4, but not for 9.0.3 so this looks good. 

Is this now fixed in general or does this only work now for some specific fields?

Will updating the reference index also add references for previously inserted images?

**Comment by sypets** [comment]
Can you please add the "bug" label? This is a bug. If the reference index is not updated, the references will not be shown in the file list which may result in files being removed (by unsuspecting editors) even though they are still being used.

-----

Current status: Reference index entry is **not** created with latest master:

* rte_ckeditor_image: dev-master
* TYPO3 11.5.25 or dev-11.5

------

I noticed that what is returned by [RteImageSoftReferenceParser::findImageTags](https://github.com/netresearch/t3x-rte_ckeditor_image/blob/master/Classes/DataHandling/SoftReference/RteImageSoftReferenceParser.php#L103) is probably wrong.

```
return [
            'content'  => implode('', $this->splitContentTags),
            'elements' => $images,
        ];

```
should be:

`return $images;`



Comparing what is passed to (the core) [ SoftReferenceParserResult::create](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/DataHandling/SoftReference/SoftReferenceParserResult.php#L48) function with an rte image tag, the result is wrapped in an extra content / elements array:

1) with rte image tag

$elements is

```
content : "<p><img ---"
elements:
  1: 
    matchString":"<img  ..."
    subst: 
     type: "db" 
     recordRef: "sys_file:17804",
     tokenID: "f6f3a30214c2f46e38d28c50e19e65c8"
     tokenValue: "17804"
```

2) with file link, it looks more like this:

 ```
 1: 
    matchString":"<a href=  ..."
    subst: 
     type: "db" 
     recordRef: "sys_file:17804",
     tokenID: "f6f3a30214c2f46e38d28c50e19e65c8"
     tokenValue: "file:17804"
```
