### ISSUE TITLE
Class 'Netresearch\RteCKEditorImage\Controller\SelectImageController' not found 

### ISSUE THREAD

**Issue by MrMooky** [netresearch/t3x-rte_ckeditor_image#46]
Installation worked fine. When I click the Image icon in the RTE, I'm greeted with this message:

<img width="709" alt="screen shot 2019-01-18 at 09 38 37" src="https://user-images.githubusercontent.com/3603346/51375003-f4a84b80-1b04-11e9-9c94-75687bdca241.png">

Looked around the usual places but could not find an answer. Anybody know how to fix that?

That's the error message inside the Log:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Netresearch\RteCKEditorImage\Controller\SelectImageController' not found | Error thrown in file /var/www/vhosts/domain.tld/typo3_src-8.7.22/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3963. Requested URL: https://www.domain.tld/typo3/index.php?route=%2Frte%2Fwizard%2Fselectimage&token=--AnonymizedToken--&P%5Btable%5D=tt_news&P%5Buid%5D=16953&P%5BfieldName%5D=bodytext&P%5BrecordType%5D=0&P%5Bpid%5D=6953&P%5BrichtextConfigurationName%5D=default&contentsLanguage=en&editorId=cke_1&bparams=data_tt_news__16953__bodytext_|ckeditor|typo3image||data_tt_news__16953__bodytext_|||onSelected

**Comment by muh-nr** [comment]
Any error logs?
Do you use the current master?

**Comment by MrMooky** [comment]
No error log. :/ We're using the latest version from TER (8.8.8).

**Comment by muh-nr** [comment]
Did you install your TYPO3 via composer?
Then it won't be possible to add the extension manually! Please install by `composer require netresearch/rte-ckeditor-image`!

When I manually install TYPO3 and also this extension, it works for me.

**Comment by muh-nr** [comment]
@MrMooky what about the current version?
