### ISSUE TITLE
Default width / height not working in BE

### ISSUE THREAD

**Issue by Razrael** [netresearch/t3x-rte_ckeditor_image#5]
Hello

First thank you for this plugin. It is exactly what I was looking for.

I was trying to configure the default image width and height in the Backend.
According to the docs, it can be done with [Page TSConfig](https://github.com/netresearch/t3x-rte_ckeditor_image#maximum-widthheight).
This setting only works in the FE though, but not the BE. So the editor still defaults to 300px and does not allow higher values.

After some debugging I found that the Editor can be changed with settings in the YAML file, but this seems to be not intended, because the config has to be on the wrong level and needs to have dots in the end.
I got it working with this for now:
```
editor:
  ...
buttons.:
  image.:
    options.:
      magic.:
        maxWidth: 924
        maxHeight: 924
```

In my opinion the config should either be taken from Page TSConfig or should be somewhere in `editor` and without the trailing dots.

Versions:
- TYPO3: 8.7.1
- t3x-rte_ckeditor_image: 8.7.1 (installed with composer from this repository)

**Comment by copitz** [comment]
You don't configure the max widths/heights in the yaml but in Page TSConfig: https://github.com/netresearch/t3x-rte_ckeditor_image#maximum-widthheight

**Comment by Razrael** [comment]
As stated above, I first configured them in Page TSConfig. But they are just ignored from the editor, it still defaults to 300.

The settings in Page TSConfig are working only in the Frontend part.

**Comment by copitz** [comment]
Just to exclude that: what are the dimensions of the image that you're trying? The dialog won't allow you to set dimensions higher than that of the image.

**Comment by Razrael** [comment]
I already ruled this out, dimensions are 960x360px.
During a very quick debugging session (I don't have much time right now), I figured something out:`\TYPO3\CMS\Core\Configuration\Richtext::getConfiguration` which is used for retrieving the configuration, is only returning the configuration from YAML, but not Page TSConfig.
Apparently it might have something to do with setting a CkEditor preset via Page TSConfig: `RTE.default.preset = Dw`.
This resets the already loaded Page TSConfig to only the loaded YAML config (see `\TYPO3\CMS\Core\Configuration\Richtext:100`)

This might or might not be a limitation of the TYPO3 implementation of CkEditor.
But knowing this, I would suggest to alternatively add a possible setting to the YAML file.

I might be able to get a bit more into the code at the weekend. But I would appreciate some assistance there.

**Comment by copitz** [comment]
I'm sorry but I just can not confirm the problem. I have following page TSConfig:

    RTE.default.buttons.image.options.magic {
        maxWidth = 1200
        maxHeight = 1000
    }

and when I use an image with f.i. 1900px width, the max width is correctly set to 1200px. Also, when I set the width to 500 and later try to set it back to 1900 it's correctly limited to 1200.

The yaml configuration doesn't have anything to do with the image dimensions in the dialog. Rather the plugin loads the image information and configuration from `\Netresearch\RteCKEditorImage\Controller\SelectImageController::infoAction`

**Comment by Razrael** [comment]
Sorry for the delay...
I created a minimal example extension for you, so you can reproduce the issue.
[sitepackage_1.0.0_201707091957.zip](https://github.com/netresearch/t3x-rte_ckeditor_image/files/1133941/sitepackage_1.0.0_201707091957.zip)

Just install it into a preferably new TYPO3 installation and include the typoscript.
You will then see, although the required TSconfig is loaded, you can't insert bigger images than 300px wide.

It is only possible if you ditch the TSconfig to load the editor preset (`Configuration/TsConfig/Rte.txt:4`) and override the default preset (`ext_localconf.php:3`; change the key `Sitepackage` with `default`.
Last resort is to simulate the TSconfig structure like I added as a comment into `Configuration/Yaml/Ckeditor/Sitepackage.yaml:38`).

**Comment by Razrael** [comment]
Small addition: It seems to be this bug: https://forge.typo3.org/issues/81381

But I don't know if this behavior is intended or not, because no one took care about it yet.

**Comment by bigahuna** [comment]
I have the same problem as described above. Tested with TYPO3 10.4.26 and 10.4.27. 

adding the following TSconfig has no effect:

`RTE.default {
	buttons.image.options.magic.maxWidth = 1000
	buttons.image.options.plain.maxWidth = 1000
}`


If I add an image in a RTE textfield, I can set the width to 1000 and all is OK. But after saving the page, the image is reduced to a width of 300px inside the RTE textfield and also in the frontend. 

But if I modify the class /typo3/sysext/core/Classes/Resource/Service/MagicImageService.php and set the protected var $magicImageMaximumWidth to 1000, everything works.

I tried all sorts of solutions, nothing works. Image inside an RTE textfield will be reduced to a with of 300px.

Hope someone can help.

Regards
Mike

**Comment by DavidBruchmann** [comment]
For the frontend you've to adjust variable like `styles.content.textmedia.maxW` too, you can find several variables concerning image measures in the constant editor.

**Comment by bigahuna** [comment]
Thanks for the reply. I set all variables to a value > 300. But I do not have to go to the frontend. As soon as I save the page in the backed, the image gets reduced to 300px width inside the RTE: 

1. I add a image in the RTE
2. The Image Properties overlay appears with a preset width of 1000
3. I click OK
4. The image is inside the RTE with a width of 1000px
5. I click the "save" button on top
6. The page reloads and the image is reduced to width = 300px inside RTE

**Comment by DavidBruchmann** [comment]
In the README is written:
```
Maximum width/height
The maximum dimensions relate to the configuration for magic images which have to be set in Page TSConfig:

# Page TSConfig
RTE.default.buttons.image.options.magic {
    maxWidth = 1020  # Default: 300
    maxHeight = 800  # Default: 1000
}
```
Did you add these settings?

**Comment by electricretina** [comment]
I am having a similar issue...
TYPO3: 11.5.33 (composer install)
PHP: 8.1.26
Browser: Brave 1.161.104

site package ext_localconf.php
```
//add the CKEditor Config
    $GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'EXT:myext/Configuration/RTE/Default.yaml';
```
site package page tsconfig: 
```
# ckeditor images
RTE.default.buttons.image.options.magic{
	maxWidth:1250
	# Default: 300
	maxHeight:1080
	# Default: 1000
}
```
I've also put the above TS in my site root page TSConfig. 

When I insert an image and change the default width from 300 it is ignored and the image is inserted into the RTE with a width of 300px. 

![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/1200661/4a3f1e66-a474-4608-960e-9da4490758a4)

After I click OK....
![image](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/1200661/a8acc8fd-5e48-49c6-933c-8a9ffe6d0508)
The image is inserted with a width of 300px

Have there been any changes on how to override this default?
