### ISSUE TITLE
"9.0.0" tag does comply tag format rules, should be "v9.0.0"

### ISSUE THREAD

**Issue by CybotTM** [netresearch/t3x-rte_ckeditor_image#50]
"9.0.0" tag does comply tag format rules, should be "v9.0.0"

**Comment by muh-nr** [comment]
@CybotTM 
Thanks for the hint. Where is this documented?

**Comment by muh-nr** [comment]
I switched back to the previous naming:
https://github.com/netresearch/t3x-rte_ckeditor_image/tags
