### ISSUE TITLE
[feature] Add image description field

### ISSUE THREAD

**Issue by kimchristiansen** [netresearch/t3x-rte_ckeditor_image#51]
Is it possible to add the image description field below title and alternative?
Or is there a reason, that this field is not available?

**Comment by muh-nr** [comment]
Hi @kimchristiansen,

would be too much effort for RTE integration.
You should use custom or media elements.

**Comment by plojewski** [comment]
@muh-nr What do you mean by "custom"?

**Comment by muh-nr** [comment]
Hi @kimchristiansen I meant you could just create a suitable Fluid Content Element (via extension) to get exactly the desired result. But currently it's to much effort for integrating it into RTE. Sorry.
