### ISSUE TITLE
Not possible to place images in RichText editor

### ISSUE THREAD

**Issue by fwiehl** [netresearch/t3x-rte_ckeditor_image#53]
My installation:
TYPO3 9.5.5
Extensions: 
rte_ckeditor 9.5.5
rte_ckeditor_image 9.0.1

It is not possible to insert an image. If you are clicking on image symbol, the window with the images are opening. But the function "Import selection" is not working!!

![Unbenannt](https://user-images.githubusercontent.com/49639260/56122624-2188c500-5f73-11e9-8463-134913fdfaf4.JPG)

**Comment by fwiehl** [comment]
I think it is a Problem of Internet Explorer 11 on Firefox Version 66.0.2 it works!

**Comment by muh-nr** [comment]
@fwiehl 
Thanks for investigating.
But sorry, we won't support IE11.
