### ISSUE TITLE
Different "Image Properties" dialogs

### ISSUE THREAD

**Issue by Razrael** [netresearch/t3x-rte_ckeditor_image#6]
After creating an image, there are two different ways to open the Image Properties dialog.
But depending on the method to open it, the dialog is not the same.

First way is over the context menu (right click on the image) and select "Image Properties", then I get this dialog:
![image](https://user-images.githubusercontent.com/8451816/27408037-17de62dc-56db-11e7-9690-035b53fdc3e9.png)

When using the way to just doubleclick on the image, I get the following dialog:
![image](https://user-images.githubusercontent.com/8451816/27408060-358e34ba-56db-11e7-8f1e-d3806d9d95d9.png)

After a link was added to the dialog through the latter dialog, the link dialog is opened on double click.
Also, when adding the link, the image is doubled in the editor.

**Comment by copitz** [comment]
Thank you - should be fixed in master and will be released with the next version

**Comment by copitz** [comment]
New version 8.7.2 is released
