### ISSUE TITLE
Generated code is not portable / deleting sys_file_processedfile breaks

### ISSUE THREAD

**Issue by vertexvaar** [netresearch/t3x-rte_ckeditor_image#60]
Also relevant: #32

Condition/Environment:
* **TYPO3** `9.5.8`
* **rte_ckeditor_image** `9.0.2`
* **fal_securedownload** `2.2.1` (maybe reproducible without, but haven't tested)
* One text CE with one image inserted with rte_ckeditor_image
* Non-public file storage

The main reason i write this issue is, that when the URL/Domain changes, images won't show up in the backend anymore, because the generated TYPO3-`dumpFile` for non-public storages includes the domain.
The other problem is sys_file_processedfile. The image shown is a processed file and upon deleting the row for the preview the image also won't show up in the backend.

A possible solution could be not using TYPO3's FAL `getPublicUrl` mechanism but adding an own eID script that handles these images in the backend to e.g. rerender processed files if they are missing.

**Comment by mcmulman** [comment]
@vertexvaar 
Should be solved in current master (not tagged yet).
Please check again.
Thanks

**Comment by vertexvaar** [comment]
Hi @mcmulman 

it seems the issue has been fixed in 7ad1bdd622f77aa338e35365d80e56acb54f44b3 for #57 

Thank you very much!
