### ISSUE TITLE
Take max width into account on save

### ISSUE THREAD

**Issue by muh-nr** [netresearch/t3x-rte_ckeditor_image#61]
Since TYPO3 9 `$magicImageService->createMagicImage(...)` does not use max width/height values for image rendering

**Comment by tmotyl** [comment]
@muh-nr @aphex13 what do you mean?
What has changed in v9 and where? how does it influence the process of inserting images in RTE?

**Comment by mcmulman** [comment]
@tmotyl you'r right, nothing changed, everything works.
Don't know what has been wrong...

**Comment by mcmulman** [comment]
The problem occured when saving an fce with images. Then the max values haven't been taken into account.
