### ISSUE TITLE
SelectImageController::97

### ISSUE THREAD

**Issue by laexus** [netresearch/t3x-rte_ckeditor_image#63]
**no:** 
'url' => $this->prettifyImgUrl($processedFile->getPublicUrl()),

**ok:**
'url' => $this->prettifyImgUrl($file->getPublicUrl()),

**Comment by CybotTM** [comment]
fixed in [9.0.4](https://github.com/netresearch/t3x-rte_ckeditor_image/releases/tag/v9.0.4)
