### ISSUE TITLE
CKEditor in TYPO3 9.5 does not work with Internet Explorer 11

### ISSUE THREAD

**Issue by nodeadman** [netresearch/t3x-rte_ckeditor_image#64]
If you want to edit a content section in Internet Explorer 11, the CKEditor throws an error in the Javascript "typo3image.js". The CKEditor does not appear and editing is not possible.

Used version:
TYPO3 9.5.9
rte_ckeditor_image 9.0.3

**Comment by thommyhh** [comment]
@nodeadman Could you please post the JS error and describe a bit better how to reproduce this error?

**Comment by nodeadman** [comment]
Console from Internet Explorer 11 displays:
SCRIPT1002: Syntaxfehler
typo3image.js (168,46)
SCRIPT5007: Die Eigenschaft "icons" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
ckeditor.js (250,489)

**Comment by prdt3e** [comment]
I can confirm (IE 11.295.18362.0)
TYPO3 9.5.9
rte_ckeditor_image 9.0.3

typo3image.js (168,46) -> syntax
ckeditor.js (250,489)  -> The "icons" property of an undefined or null reference can not be retrieved.

**Comment by christophmellauner** [comment]
Arrow functions are not supported in IE11!

https://github.com/netresearch/t3x-rte_ckeditor_image/blob/master/Resources/Public/JavaScript/Plugins/typo3image.js#L168

**Comment by prdt3e** [comment]
@christophmellauner do you have an idea for a workaround?

**Comment by christophmellauner** [comment]
yes added a pull request https://github.com/netresearch/t3x-rte_ckeditor_image/pull/66

**Comment by jvanderkroon** [comment]
Tested the patch on IE11 and it works.

**Comment by thommyhh** [comment]
Seams to be solved with #66.
