### ISSUE TITLE
Custom width & height not respected in FE if set within an extension

### ISSUE THREAD

**Issue by kraemer-igroup** [netresearch/t3x-rte_ckeditor_image#68]
Hello,

I configured a custom width & height for my images within the default.tsconfig file of my template extension. As long as I was logged in (BE) everything worked fine. But without an active backend session my images always were rendered with a maximum width of 300px.

There is this bug in TYPO3 which does not respect extension TSConfig in FE: https://forge.typo3.org/issues/87068

When putting the "RTE.default.buttons.image.options.magic" config into my root page it worked immediately without having an active BE session. By the way, the maximum width of 300px came from the MagicImageService class.

Maybe this helps somebody and maybe even makes it into the documentation. And maybe this also was the issue in #16.

**Comment by CybotTM** [comment]
fixed in [9.0.4](https://github.com/netresearch/t3x-rte_ckeditor_image/releases/tag/v9.0.4)
