### ISSUE TITLE
Unchecking enlarge on click not working 

### ISSUE THREAD

**Issue by ebincm** [netresearch/t3x-rte_ckeditor_image#69]
Use Case in 
TYPO3 9.5.9 - LTS
rte_ckeditor_image - 9.0.3
Added an image with a popup in the ckeditor by enabling enlarge on click checkbox. It saves correctly in the CKEditor with the data-zoom attribute as true.
But when unchecking `enlarge on click` this data-zoom attribute persists & unable to save the same image without a popup.

**Comment by hoermannklaus** [comment]
I encountered the same problem having TYPO3 version 9.5.13 and rte_ckeditor_image version 9.0.4.

**Comment by zelcode** [comment]
Hey people,
is there life here, there is allready 10.4.5 LTS

You can check if this is good enough, tested on 10.4.5 LTS and `this` dev-10.x

```javascript
      if ($zoom.prop('checked')) {
        // When saving the zoom property is saved as the new `zoom` attribute
        attributes['data-htmlarea-zoom'] = true
      // If unchecked, remove zoom attributes
      } else if (attributes['data-htmlarea-zoom'] || attributes['data-htmlarea-clickenlarge']) {
        attributes = null
      }
      return attributes
```
