### ISSUE TITLE
replaced images are not replaced on ckeditor

### ISSUE THREAD

**Issue by stephanederer** [netresearch/t3x-rte_ckeditor_image#72]
- TYPO3 9.5.8
- rte_ckeditor_image 9.0.4

If you replace an images on Filelist the images aren't changed on ckeditor, if the image is already on a page.

**Comment by mcmulman** [comment]
@stephanederer  
Should be solved in current master (not tagged yet).
Please check again.
Thanks

**Comment by stephanederer** [comment]
Seems to be solved, thank you!
