### ISSUE TITLE
[ImageLinkRendering] $attrSearchPattern regex

### ISSUE THREAD

**Issue by UNI49** [netresearch/t3x-rte_ckeditor_image#73]
Hello,

In the **ImageLinkRendering** controller, is this possible to have a regex (for `attrSearchPattern`) which consider that if attr begin with a simple quote it end with a simple one, and same for double quote.
In major french keyboard/keymap there is no ’ (which is the different from ' ) end this thing can leads to parsing problems.

Let me know if it's a good idea or not.

Thanks for help.

**Comment by muh-nr** [comment]
Hi @UNI49 
So you want to use quotes within the attributes (as its value)?
E.g. as an alt text?
At the moment unfortunately I don't have any time for features like that, but feel free to post a solution if you have one.
