### ISSUE TITLE
Not working at IE 11.

### ISSUE THREAD

**Issue by akhamuliak** [netresearch/t3x-rte_ckeditor_image#76]
JS is not compatible with IE 11.

I have a default RTE settings and If I'm including a rte_ckeditor_image it's working fine at all browsers except IE 11.

```
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }

```

SCRIPT5022: Script error for "https://[domain]/typo3/sysext/rte_ckeditor/Resources/Public/JavaScript/Contrib/vendor/promise.js?t=J8Q9"

**Comment by mcmulman** [comment]
Hi @akhamuliak 
you should use a modern browser for editing!

**Comment by akhamuliak** [comment]
@mcmulman that's true :)

 But it will be a rude answer for the client.

**Comment by mcmulman** [comment]
@akhamuliak 
When should they ever learn? ;)
Feel free to fix it, I unfortunately don't have the time to support a browser from 2013.
