### ISSUE TITLE
no wrap in lightbox link

### ISSUE THREAD

**Issue by baggyownz** [netresearch/t3x-rte_ckeditor_image#79]
When I select an image and look at the URL in source code mode, the complete URL path including http is there. Basically everything okay so far. However, when outputting or rendering in the ImageRenderingController.php file, the check for `if (!$this->isExternalImage())` determines that the URL is an external one, although it is not so and there is exactly the same URL stands which is used for the FE.

Can't the review be left out?

**Comment by prdt3e** [comment]
Then something is wrong with your typo3!
Maybe set with allowTags or entryHTMLparser_db?
I have to remember back ...

For the background:
The URL is temporarily displayed in the editor, but is modified when it is saved.
The core function is responsible for saving  (https://api.typo3.org/9.5/_rte_html_parser_8php_source.html).
You see TS_images_db (// Convert absolute to relative url).

This function is no longer available in version 10!

**Comment by prdt3e** [comment]
Please do a print_r in the function isExternalImage on $srcAbsoluteUrl.
The function is required. Someone may include an external image in the editor which cannot be parsed.

**Comment by mcmulman** [comment]
@baggyownz 
Did you find a solution?

**Comment by baggyownz** [comment]
@mcmulman 
Sorry, I don't have a solution yet.
At the moment I'm also very busy, so I can't answer any faster. sorry
