### ISSUE TITLE
Conflict between 2 extensions  typo3link and typo3image (rte_ckeditor_image)

### ISSUE THREAD

**Issue by cwplus** [netresearch/t3x-rte_ckeditor_image#86]
In a new installation of typo3 v8.7, and just after activating rte_ckeditor_image v: 8.9.0:
- When we select a word in an RTE, to make it in bold -strong-, and we add a link on this same word, we noticed that if we continue to modify this link, a new tag -strong- is also added .
- For your information, if you deactivate the extension, this bug disappears

![rte_ckeditor_image_1](https://user-images.githubusercontent.com/5727109/84998209-d4444c80-b14f-11ea-8372-27a51f49d6d8.png)
![rte_ckeditor_image_2](https://user-images.githubusercontent.com/5727109/84998207-d3abb600-b14f-11ea-9d02-0dd4d0215242.png)
![rte_ckeditor_image_3](https://user-images.githubusercontent.com/5727109/84998205-d3abb600-b14f-11ea-8f00-7d64aecb59a7.png)
![rte_ckeditor_image_4](https://user-images.githubusercontent.com/5727109/84998204-d3131f80-b14f-11ea-829a-ee4756ed7144.png)

**Comment by mcmulman** [comment]
@cwplus 
Sorry but I couldn't reproduce in TYPO3 9.

**Comment by cwplus** [comment]
il have this bug for typo3 8.7
