### ISSUE TITLE
anyone made t3x-rte_ckeditor_image work under TYPO3 9.5 and how?

### ISSUE THREAD

**Issue by yurigoul** [netresearch/t3x-rte_ckeditor_image#87]
Working under typo3 9.5 with a recent bootstrap_package

I have followed all the steps in the readme.md but the add image button does not appear. When searching for possible conflicts I found that this seems to be blocked in [bootstrap_package by design](https://github.com/benjaminkott/bootstrap_package/issues/315#issuecomment-347880062). 

There simply is no difference with or without the plugin. I have turned off the RTE from bootstrap_package in the settings. I have added the page_tsconfig to the root page and to the template. I have added the line '$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'EXT:my_ext/Configuration/RTE/Default.yaml';' also to the aditionalConfiguration.php to see  if anything happens. Is there something that I am missing? 

The thing is that I know how to follow instructions to make something work but this is growing above my head. And I really want to be able to add images through RTE

**Comment by prdt3e** [comment]
Good evening,
the problem you are saying is because bootstrap_package has its own Default.yaml (bootstrap_package / Configuration / RTE / Default.yaml).

Which was registered as follows (bootstrap_package/ext_localconf.php)
```
$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['bootstrap'] = 'EXT:bootstrap_package/Configuration/RTE/Default.yaml';
```

(bootstrap_package/Configuration/TsConfig/Page/RTE.tsconfig)
```
RTE {
    default {
        preset = bootstrap
    }
}
```

And this configuration has to be overwritten.
What does it mean exactly?

You have to copy the configuration bootstrap_package / Configuration / RTE / Default.yaml to a new file.
Then insert the "imports" of EXT: rte_ckeditor into the configuration (reademe.md).

Then make Typo3 aware of the new configuration:
```
// EXT:my_ext/ext_localconf.php`
$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'EXT:my_ext/Configuration/RTE/Default.yaml';
```

And lastly, you have to tell the editor to load your configuration instead of boostrap_package.
```
RTE.default.preset = default
```
(https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/UsingSetting/Index.html)

I hope I could help

**Comment by yurigoul** [comment]
Also good evening where I am,
I'm very glad to get this insight, because it might mean there is an answer somewhere.

However I tried to follow this to the letter (I copy pasted everything, even folder names - as I did before) - but then the plugin my_ext does not get registered anywhere:

![Screen Shot 2020-06-20 at 22 07 16](https://user-images.githubusercontent.com/11797611/85210769-0b2e8400-b343-11ea-85e9-06dce7dbbf4c.png)

This is the structure of the folder: 

![Screen Shot 2020-06-20 at 22 05 27](https://user-images.githubusercontent.com/11797611/85210841-b50e1080-b343-11ea-8cdc-2314008bc303.png)

I checked the permissions of files and folders, all should be ok.

I can force the system to registere the plugin by adding the content of my_ext/ext_localconf.php the to the AdditionalConfiguration.php, but then all kinds of other errors are the result when opening a view where an RTE is. 

What am I missing here?

**Comment by prdt3e** [comment]
It looks very nice. We are close.

- is the file filled? It cannot be empty!
- are the write permissions of the file correct?
- Check capitalization!
- Cache in the install tool deleted?

**Comment by yurigoul** [comment]
- The file is not empty. I have copied the contents of bootstrap_package / Configuration / RTE / Default.yaml into my Default.yaml for testing purposes
- files are 664, folders 775, files are utf8 
- if you can find errors in the capitalization, tell me - I added the contents of my_ext in a zip file
- I am using 9.5 so I use Admin tools > maintenance > Flush TYPO3 and PHP Cache

As I said: typo3 only registers it when I add my_ext/ext_localconf.php the to the AdditionalConfiguration.php

I have added the zip file here, I have no idea anymore how to make the system notice the existence of my_ext.

[my_ext.zip](https://github.com/netresearch/t3x-rte_ckeditor_image/files/4808970/my_ext.zip)

**Comment by prdt3e** [comment]
I'll download the extension tonight and watch it for you.
And test it with Boostrap_Package.

**Comment by prdt3e** [comment]
But what strikes me immediately.
You have no "ext_emconf.php".
So you can't install your extension!
So file paths and PHP code are irrelevant because the extension for Typo3 is unknown.

**Comment by yurigoul** [comment]
Wait, but why is that not in the readme.md? I knew something was missing. 

In the meantime I did a clean install with just bootstrap_package and rte_ckeditor_image and a front page. 

I now made me a ext_emconf.php with the following info, but it still won't read it after emptying cache, php cache and autoload info  - because $GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] is still EXT:rte_ckeditor/ etc and not EXT:my_ext etc.

$EM_CONF[$_EXTKEY] = array ( 
    'title' => 'My very own',
    'description' => 'My extension for images in RTE',
    'category' => 'Misc',
    'version' => '1.0.0',
    'state' => 'stable',
    'author' => 'YuriGoul'
);

I even copied the ext_emconf.php from rte_ckeditor_image and changed the info into mine - no dice

Does it need autoload info even though I do not have classes?

**Comment by prdt3e** [comment]
Provide me again with your current extension for download. I will watch tomorrow immediately.

**Comment by yurigoul** [comment]
[my_ext.zip](https://github.com/netresearch/t3x-rte_ckeditor_image/files/4817351/my_ext.zip)

I have tried uploading this through admin tools/extensions and it simply says 'Extension my_ext is not available'

I am now going through the [9.5 documentation for extension writing](https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html) and it seems to suggest another way to register this.

**Comment by yurigoul** [comment]
Ok, I got it to work by adding it to my AdditionalConfiguration.php with the absolute path to my Default.yaml

- with the bootstrap_rte turned of in Backend -> Admin Tools -> Site Configuration -> Extension Configuration -> bootstrap_package -> Disable RTE
- using the original content given for the Default.yaml from the readme.md

Now to finding the right php command to set just the absolute path 
--

The thing is that we can not call the file using EXT: because it is not recognized as an extension and the only thing we want is to have the Default.yaml read. According to what I read in the 9. documentation for extension writing the AdditionalConfiguration.php would be a better place for that.

**Comment by yurigoul** [comment]
For me to make this work under Typo3 9.5 I did the following:

- Install the rte_ckeditor_image plugin 9.0.4 or newer
- Add the Default.yaml with the content from the readme.md to /typo3conf/ext/my_ext/Configuration/RTE/  - but in theory it could be anywhere
- skip turning it into a extension by adding a ext_localconf.php or a ext_emconf.php
- created or add the following to /my typo3conf/AdditionalConfiguration.php: 

`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = $_SERVER['DOCUMENT_ROOT'] . '/typo3conf/ext/my_ext/Configuration/RTE/Default.yaml';`

- Optional step since it seems to work either way: If you have the bootstrap_package turn off that RTE with with the bootstrap_rte turned of in Backend -> Admin Tools -> Site Configuration -> Extension Configuration -> bootstrap_package -> Disable RTE -> check!
- Add RTE.default.preset = default to your Page TSConfig or your template's TSConfig (I did both for good measures)
- Flush cache at BE -> Admin Tools > Maintenance -> Flush TYPO3 and PHP Cache
- Check if the path is correct at BE -> System -> Configuration -> $GLOBALS['TYPO3_CONF_VARS'] -> RTE -> Presets -> default
- ....
- Profit!

-- 

If anyone has anything to add - for instance to make it more elegant - be my guest

**Comment by prdt3e** [comment]
Nevertheless, I would like to note that for an overlay of bootstrap_package an extension should be created via www.sitepackagebuilder.com. This is properly registered and prevents templates from being made in Fileadmin.

**Comment by dmmediaKS** [comment]
> 
> 
> For me to make this work under Typo3 9.5 I did the following:
> 
>     * Install the rte_ckeditor_image plugin 9.0.4 or newer
> 
>     * Add the Default.yaml with the content from the readme.md to /typo3conf/ext/my_ext/Configuration/RTE/  - but in theory it could be anywhere:
> 
> 
> > # EXT:my_ext/Configuration/RTE/Default.yaml
> > imports:
> > # Import default RTE config (for example)
> > - { resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml" }
> > # Import the image plugin configuration
> > - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }
> > editor:
> > config:
> > # RTE default config removes image plugin - restore it:
> > removePlugins: null
> 
>     * skip turning it into a extension by adding a ext_localconf.php or a ext_emconf.php, you do not need that here
> 
>     * create or add the following to /my typo3conf/AdditionalConfiguration.php:
> 
> 
> > $GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = $_SERVER['DOCUMENT_ROOT'] . '/typo3conf/ext/my_ext/Configuration/RTE/Default.yaml';
> 
>     * Optional step since it seems to work either way: If you have the bootstrap_package turn off that RTE with with the bootstrap_rte turned of in Backend -> Admin Tools -> Site Configuration -> Extension Configuration -> bootstrap_package -> Disable RTE -> check!
> 
>     * Add `RTE.default.preset = default` to your Page TSConfig or your template's TSConfig (I did both for good measures)
> 
>     * Flush cache at BE -> Admin Tools > Maintenance -> Flush TYPO3 and PHP Cache
> 
>     * Check if the path is correct at BE -> System -> Configuration -> $GLOBALS['TYPO3_CONF_VARS'] -> RTE -> Presets -> default
> 
>     * Try adding an image in an RTE on your site
> 
>     * ....
> 
>     * Profit!
> 
> 
> --
> 
> If anyone has anything to add - for instance to make it more elegant - be my guest

I did it the same way but got this message:

Fatal error: Allowed memory size of 134217728 bytes exhausted (typo3_src-9.5.19/vendor/symfony/yaml/Unescaper.php on line 50

**Comment by Chrisswald** [comment]
It seems not to be a problem of the extension but of your php settings. Maybe this helps: https://stackoverflow.com/questions/4096582/allowed-memory-size-of-x-bytes-exhausted

**Comment by dmmediaKS** [comment]
> 
> 
> It seems not to be a problem of the extension but of your php settings. Maybe this helps: https://stackoverflow.com/questions/4096582/allowed-memory-size-of-x-bytes-exhausted

If I increase the memory limit it should go?

**Comment by prdt3e** [comment]
Or something is wrong with the .yaml file.
It's not always that easy (indentations, breaks)

**Comment by mcmulman** [comment]
Works for me in TYPO3 9.5.*
