### ISSUE TITLE
Add custom class for <img> tag

### ISSUE THREAD

**Issue by agendartobias** [netresearch/t3x-rte_ckeditor_image#88]
Hey, is there any way to add custom class for img tag when adding image? I tried to add something like that in Plugin.yaml but it dont work attributes: { 'class': 'testrene' }

`editor:
  externalPlugins:
    typo3image: { resource: "EXT:rte_ckeditor_image/Resources/Public/JavaScript/Plugins/typo3image.js", route: "rteckeditorimage_wizard_select_image", attributes: { 'class': 'testrene' } }`

**Comment by prdt3e** [comment]
We have always done this with the <p> tag around it.
Have added a custom style to the editor (stylesSet).
The feature is being planned. (alignment / class)

**Comment by mcmulman** [comment]
@agendartobias 

You can add a custom class for all images via

```
lib.parseFunc_RTE {
    // default class for images in bodytext
    nonTypoTagStdWrap.HTMLparser.tags.img.fixAttrib.class {
      default = my-custom-class
    }
}
```

But I'm already have a version with an optional field for custom classes for each image.
Let's see if I'm able to extract it...

**Comment by mcmulman** [comment]
Found it... please have a look at #108
