### ISSUE TITLE
Context Menu -> Image Properties is not clickable anymore after content element is saved

### ISSUE THREAD

**Issue by christophrunkel** [netresearch/t3x-rte_ckeditor_image#89]
Detected in Typo3 9.5.19, rte_ckeditor_image 9.04 PHP 7.3

Insert an Image, Check the Click enlarge box then quit the dialog. Right Click on the image, select "Image properties" -> dialog appears. You can edit title, click enlarge etc.

Now save the content element and try again. Nothing happens when you click on the image.

**Comment by prdt3e** [comment]
#69

**Comment by typo3rel** [comment]
in my custom yaml i fixed it with:

```
editor:
  config:
    extraAllowedContent:
      - a[!href,document-href,tel]
      - img[*]
```

the plugin needs/want the data-htmlarea-file-uid attribute in the img tag 

```

if (img && img.getAttribute('data-htmlarea-file-uid')) {
                        edit(
                            img.getAttribute('data-htmlarea-file-table') || 'sys_file',
                            img.getAttribute('data-htmlarea-file-uid'),
                            img.getAttributes()
                        );
                    }
```

**Comment by typo3rel** [comment]
extraAllowedContent: '*(*)[data-*]'

**Comment by mcmulman** [comment]
@christophrunkel 
Should be solved in current master (not tagged yet).
Please check again.
Thanks
