### ISSUE TITLE
missing / desired features 

### ISSUE THREAD

**Issue by wini2** [netresearch/t3x-rte_ckeditor_image#9]
hello,
this issue should better be placed to pull requests - but becuase of reasons i don' t know, i can't create one. 

in the rtehemlarea i achived it to get nearly the same output like using normal images by using the features of the extra-static-template of the htmlarea, my own amateurish typoscript and javascript. It would be great, if i can get achive a similar result with the ckeditor. to become a little bit more speicific: 
- the editor should have the opportunity to specify margin/padding for the image/figure in the insert-dialog.
- the image-tag should be inside of a figure-tag,
- which should also include an figcaption. 

thanks a lot

**Comment by copitz** [comment]
Hi,

to open a pull request, you first have to fork this repository. As for your wishes:

- I don't see a need for the editor to specify margin/padding or any other css properties - one should rather use css classes for this. They can for now be configured for and be selected from the stylesSet. What we could do, is to make the classes for img tags available in the properties dialog as well which however seems quite complex
- About the figure tag: Yes, I'm thinking about a TypoScript configuration endpoint where you could change the rendering of the images

**Comment by erredeco** [comment]
I would just include a float:left and float:right dropdown
