### ISSUE TITLE
Click enlarge gets lost when operation in parent element is done

### ISSUE THREAD

**Issue by christophrunkel** [netresearch/t3x-rte_ckeditor_image#90]
Detected in Typo3 9.5.19, rte_ckeditor_image 9.0.4, PHP 7.3

Create a table with one row and two cells.
Insert an image in the left cell, choose "Click enlarge" then quit the dialog.
After that select the containing td element on the bottom of the editor and change the alignment to right or centered and save the content element. Click enlarge link gets lost.

**Comment by mcmulman** [comment]
@christophrunkel 
Sorry, but couldn't reproduce on TYPO3 9.
Maybe you have special configuration for table handling?
Please check with a default system.
Does it still happen?
