### ISSUE TITLE
On localized pages, rte_ckeditor_image does not use image's localized alternative text, but incorrectly default language alternative text

### ISSUE THREAD

**Issue by Abdull** [netresearch/t3x-rte_ckeditor_image#91]
Environnment:
* TYPO3 9.5.20
* rte_ckeditor_image 9.0.4

Files uploaded to fileadmin / filelist / Dateiliste can be given an "alternative text" for each language the TYPO3 installation is set up with.

Such alternative text is useful e.g. for images as it gives a textual description for images. Such description describes images to users with visual impairments, e.g. blind users.

**I noticed that even when a translated alternative text is given to an image, this translated alternative text is not used in images added inline in RTE bodytexts. Intead, incorrectly the default language alternative text is used.**

Steps to reproduce this bug:
* Upload image with filelist.
* Give this image an "Alternative Text" in the default language: "Standard-Sprache Alternative Beschreibung" (in *this* scenario, "Deutsch" is the default language).
* In that image's fielist "file metadata" backend interface, select another language localization within the language dropdown, e.g. "English [NEW]".
* Give this image an "Alternative Text" in the English localization: "English language alternative description".
* Select or create an English localization of some page.
* Create a new or edit an existing "Text & Media" content element on the English localization of that page.
* In the bodytext RTE Rich Text Editor, add to this English content element the aforementioned image: Click on the "Image (?)/Bild" RTE widget. In the popup, select aforementioned uploaded image.
* A new popup appears: "Image properties (?)/Bildeigenschaften". "Alternative Text" INCORRECTLY shows the "Default (Deutsch)" alternative text, instead of the context-correctly English alternative text.
* Click "OK".
* Click Save for saving the English page updates.
* Inspect the frontend result of this English page:
* Result: The English localization of this page INCORRECTLY uses the German (default) localization for the image's alt attribute.
* Expected result: <img alt="English language alternative description" ...>
* INCORRECT actual result: <img alt="Standard-Sprache Alternative Beschreibung" ...>
* "What's the problem?" This breaks accessible alternative descriptions for localized images in our TYPO3 installation.

**Comment by AndreasMueller75** [comment]
Can't reproduce this behaviour. After creating a new translation of an page or content element you have to make it accessible. Otherwise the content of the default language (if activated) will be used. There is no separate language handling.

**Comment by agendartobias** [comment]
Hey, we have the same problem with TYPO3 v11.5 and rte_ckeditor_image 11.0.14. If i set image ALT attribute in Filelist for primary and secondary language it shows this attribute in primary language ok, but in secundary language it shows ALT attribute in primary language.

If you like you can contact me and i can show you how to reproduce it.
