### ISSUE TITLE
RTE.default.proc.overruleMode

### ISSUE THREAD

**Issue by prdt3e** [netresearch/t3x-rte_ckeditor_image#97]
https://github.com/netresearch/t3x-rte_ckeditor_image/blob/28e3ba729474a9a2b99afea0732994942638fc4d/ext_localconf.php#L9

https://github.com/netresearch/t3x-rte_ckeditor_image/issues/75#issuecomment-671932654

**Comment by mcmulman** [comment]
Thanks for your hint.
Changed.
